### ISSUE TITLE
Custom editor for mice missing

### ISSUE THREAD

**Issue by ti1336** [z3ntu/RazerGenie#10]
Hi,

i'm trying to use my naga chroma on my office computer with an MX Linux distribution, but i'm unable to make it works...
I've trying some solved issues, but i'm still doing something wrong :/
It's important for me, my left arm is paralized and this mouse is very helpfull for me.

thank you in advance

PS : sorry for my bad english
![36474595-45ca79f0-16f8-11e8-9da8-e19d54e46681](https://user-images.githubusercontent.com/36693572/36474940-6e7edf52-16f9-11e8-8716-6674d83b027f.png)

**Comment by z3ntu** [comment]
Yes, this isn't implemented yet. But the custom editor doesn't add any functionality except custom lighting  on the mouse.

**Comment by nightsky30** [comment]
Aww nuts, found this when working on https://github.com/openrazer/openrazer/issues/322

![screenshot_2018-07-29_09-14-51](https://user-images.githubusercontent.com/6024315/43367260-e8b73fb6-930f-11e8-9009-dd72bd043169.png)

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
