### ISSUE TITLE
UI not drawing 

### ISSUE THREAD

**Issue by ckozler** [z3ntu/RazerGenie#101]
Or I have missed something entirely? I have Razer Kraken Ultimate 7.1. Audio works and everything is fine but the UI for RazerGenie (for me) looks unfinished or something isnt drawing correctly

Some details:

- fedora 33 100% updated to current (I did dnf upgrade and reboot before doing openrazer install)
- added my user account (ckozler) to gplugdev 
- rebooted after openrazer install 
- awesomewm with gnome under it (not gnome-shell)
- RPM of qt5 installations below

> sudo rpm -qa | grep -i qt5
qca-qt5-ossl-2.3.1-2.fc33.x86_64
qt5-qttools-common-5.15.1-1.fc33.noarch
qt5-qtmultimedia-5.15.1-1.fc33.x86_64
phonon-qt5-backend-gstreamer-4.10.0-4.fc33.x86_64
qt5-srpm-macros-5.15.1-1.fc33.noarch
adwaita-qt5-1.1.3-4.fc33.x86_64
qt5-qtsensors-5.15.1-1.fc33.x86_64
qt5-qtdeclarative-5.15.1-1.fc33.x86_64
qca-qt5-2.3.1-2.fc33.x86_64
qt5-qtwebchannel-5.15.1-1.fc33.x86_64
qt5-qtwayland-5.15.1-1.fc33.x86_64
dbusmenu-qt5-0.9.3-0.25.20160218.fc33.x86_64
qt5-qtx11extras-5.15.1-1.fc33.x86_64
qt5-qtlocation-5.15.1-1.fc33.x86_64
qt5-qtsvg-5.15.1-1.fc33.x86_64
qt5-qtspeech-5.15.1-1.fc33.x86_64
qt5-qttools-libs-designer-5.15.1-1.fc33.x86_64
qt5-qtquickcontrols-5.15.1-1.fc33.x86_64
phonon-qt5-4.11.1-6.fc33.x86_64
polkit-qt5-1-0.113.0-5.fc33.x86_64
poppler-qt5-0.90.0-6.fc33.x86_64
qt5-qtwebkit-5.212.0-0.52.alpha4.fc33.x86_64
qt5-qtspeech-speechd-5.15.1-1.fc33.x86_64
qt5-qtxmlpatterns-5.15.1-1.fc33.x86_64
libaccounts-qt5-1.16-2.fc33.x86_64
qt5-qtbase-common-5.15.1-7.fc33.noarch
qt5-qtbase-5.15.1-7.fc33.x86_64
qt5-qtbase-gui-5.15.1-7.fc33.x86_64
qt5-qtnetworkauth-5.15.1-1.fc33.x86_64
qt5-qtscxml-5.15.1-1.fc33.x86_64

**Comment by z3ntu** [comment]
Can you take a screenshot of the application please? I'm not really sure what you're talking about.

**Comment by z3ntu** [comment]
Closing since there has been no response.
