### ISSUE TITLE
Device type not implemented - Mamba Elite (1532:006C)

### ISSUE THREAD

**Issue by Jayman2000** [z3ntu/RazerGenie#103]
### Steps to reproduce
1. Make sure that a Razer Mamba Elite is connected to your system.
2. Open RazerGenie.
3. Make sure that the Mamba Elite is selected in RazerGenie.
4. Click "Open custom editor" button.

### Result
A new window appears. That window will say "Device type not implemented! Please open an issue in the RazerGenie repository. Device type: mouse".

### Software versions
OS: Arch Linux
Kernel: 5.9.14.arch1
OpenRazer: 2.9.0
RazerGenie: 0.9.0

**Comment by z3ntu** [comment]
Handled by #10
