### ISSUE TITLE
(Noob post) The daemon didn't detect a device that is connected

### ISSUE THREAD

**Issue by try-except** [z3ntu/RazerGenie#107]
Hi, switched from windows to manjaro linux a couple of days ago and I'm trying to get my razer devices to work. I have installed OpenRazer and RazerGenie, but RazerGenie says the daemon hasn't detected any device.
I have a Naga Hex, Black Widow 2016 and Kraken TE

**Comment by z3ntu** [comment]
Have you looked at https://github.com/openrazer/openrazer/wiki/Troubleshooting already?

**Comment by try-except** [comment]
> Have you looked at https://github.com/openrazer/openrazer/wiki/Troubleshooting already?

Hi, yes I have read the Troubleshooting guide

**Comment by z3ntu** [comment]
Can you please run these commands and post the output?
* `sudo dkms install openrazer-driver/2.9.0`
* `sudo modprobe razerkbd`
* `openrazer-daemon -Fv`
