### ISSUE TITLE
Fedora 33 Razergenie 'Image download disabled'

### ISSUE THREAD

**Issue by jdotpeg** [z3ntu/RazerGenie#109]
I've recently hoped off the windows train so please bear with me.
I've gone through the process stated on the website for installing RazerGenie onto my fedora 33 system. i get all the way to the little RazerGenie window popping up on my screen and in the left panel i have a blue box stating "Image download disabled 'Razer Naga Trinity'".

This is problem one however i have two other Razer items that are listed as supported on the site but are not showing on the panel either.

**Comment by z3ntu** [comment]
Hi,
1. The image download can be enabled in the settings which are reachable with the button in the bottom left corner of the main UI.
2. Can you send the output of `lsusb | grep 1532` ? But given that the Naga Trinity appears most parts of the stack appear to work correctly.

**Comment by jdotpeg** [comment]
Not to worry, ive since added a brain cell to the bank. Im looking for a tool to change the key bindings on my razer gear. I use an MMO mouse (Naga trinity) and a game pad (Tartarus pro) for my Job and gaming. Since i switched over to linux i haven't been able to figure out a way to set my key bindings. I thought that this software was what i needed to do that and ive since realised its just to change the lights. Still searching for a way to keybind if anyone knows of one :/

**Comment by z3ntu** [comment]
See https://polychromatic.app/docs/faqs/#can-i-remap-keys
