### ISSUE TITLE
Some error output

### ISSUE THREAD

**Issue by ohmyarch** [z3ntu/RazerGenie#11]
https://paste.kde.org/pvsra1hsf/r3oos6

**Comment by z3ntu** [comment]
"This paste is password protected"

**Comment by ohmyarch** [comment]
Sorry about that, fixed.

**Comment by ohmyarch** [comment]
In addition, version of openrazer is 2.2.1

**Comment by z3ntu** [comment]
This is actually an issue in the daemon so it *should* be an issue in the openrazer repository (you can't know of course :wink: )
Anyways I have prepared a patch that just needs to be tested but we'll publish a new bugfix release soon.

**Comment by z3ntu** [comment]
Your issue will be fixed by https://github.com/openrazer/openrazer/pull/537

**Comment by z3ntu** [comment]
v2.2.2 is out.
