### ISSUE TITLE
the application is not responding ，macOS big sur

### ISSUE THREAD

**Issue by TreviD** [z3ntu/RazerGenie#111]
I have compiled on macOS, but the generated app does not run, indicating that the application is not responding。
I compiled with the following command
```
meson --prefix=/tmp/RazerGenie.app --bindir=Contents/MacOS builddir
ninja -C builddir install
rm -rf /tmp/RazerGenie.app/share
install_name_tool -change /tmp/RazerGenie.app/lib/libopenrazer.0.dylib @executable_path/libopenrazer.0.dylib /tmp/RazerGenie.app/Contents/MacOS/razergenie
cp builddir/subprojects/libopenrazer/libopenrazer.0.dylib /tmp/RazerGenie.app/Contents/MacOS/
macdeployqt /tmp/RazerGenie.app
```

**Comment by z3ntu** [comment]
Not sure, last I tried it still worked fine. I might try soon on my VM to see whether there's a new problem. Also I can't really provide any support for razer_test & RazerGenie on macOS.

**Comment by z3ntu** [comment]
Cannot reproduce and no response, closing.
