### ISSUE TITLE
Naga Trinity Side Button Support

### ISSUE THREAD

**Issue by BamaJoe411** [z3ntu/RazerGenie#112]
In #80 I was told that configuring the side plates on the Nage Trinity was already added to RazerGenie if I compiled from source. I have compiled it from source and I still don't see where to configure the side plates. 
![FG2wuhS](https://user-images.githubusercontent.com/392363/111742673-f8f45e80-885e-11eb-8ef9-1a0b130ac15b.png)

**Comment by z3ntu** [comment]
Hi, sorry for the misleading comment in the other issue, there are other mice where my comment applies but apparently not the Naga Trinity. It seems that it actually only has brightness and the static effect implemented in openrazer, I think you'll want to track https://github.com/openrazer/openrazer/issues/1433 for progress on that front. The Naga Trinity seems to be a bit special compared to other devices so the author of the device support hasn't implemented more.

**Comment by z3ntu** [comment]
This is not an issue in RazerGenie, and the linked OpenRazer issue already tracks this. Closing.
