### ISSUE TITLE
"Image download disabled"

### ISSUE THREAD

**Issue by YamiYukiSenpai** [z3ntu/RazerGenie#115]
![Screenshot_20210502_025259](https://user-images.githubusercontent.com/13153124/116805032-829b7b00-aaf1-11eb-8532-b32a0266a6ab.png)
How can I fix this?

This was installed via Flatpak

**Comment by Actery** [comment]
i have the same problem with opensuse

**Comment by z3ntu** [comment]
You can press the settings button in the lower left corner (potentially the icon is missing for you?) and enable image download there.

**Comment by DevSnobo** [comment]
> You can press the settings button in the lower left corner (potentially the icon is missing for you?) and enable image download there.

Could you specify where exactly this icon should be placed (or is there a shortcut to open the settings)? I have the same issue.

**Comment by z3ntu** [comment]
In the very bottom left; left of the "Daemon version" label should be this button. It might be "invisible" if the icon is missing but I think hovering the mouse over it should show some effect.

**Comment by z3ntu** [comment]
Closing as this is an intended feature, even though it could probably be a bit more obvious that you can enable image download in the settings.
