### ISSUE TITLE
Add custom editor for razer tartarus V2 keypad 

### ISSUE THREAD

**Issue by haenenma** [z3ntu/RazerGenie#116]
Can the custom editor be enabled for the Tartarus V2 keypad ?

**Comment by z3ntu** [comment]
Hi, if you want to have the "cheap option", you can enable this option https://github.com/z3ntu/RazerGenie/blob/master/meson_options.txt#L1 during compile time and then you have a very similar feature but with an uglier UI.
If you want to add proper support then you'll need to create a json similar to https://github.com/z3ntu/RazerGenie/blob/master/data/matrix_layouts/razerdefault22.json that maps labels and a layout to the different keys on the keyboard so it can be displayed nicely in the UI. And then add a block here https://github.com/z3ntu/RazerGenie/blob/fcbe0980fbeef08da537a48fb7a72652c3784b4b/src/customeditor/customeditor.cpp#L65-L76 to actually use the json. If you have any questions, feel free to ask.

**Comment by haenenma** [comment]
Okay thanks a lot for your help. I will try first for the cheap option.
