### ISSUE TITLE
Razer nommo chroma problem with sound level.

### ISSUE THREAD

**Issue by arisviel** [z3ntu/RazerGenie#119]
Good afternoon, did not find an issue for this problem.
I am using a dual-boot system with linux and Windows. The speakers are connected via usb. When I finish a session in Windows, and let's say the speakers were at 25% volume at that moment. Then Linux sees it as 100% loudness, i.e. when the volume is set to 100% in linux, in fact it is 25% of the power of the speakers. And I can adjust the sound within 0-25%, but not more. If I want to be louder, I have to boot Windows and set it to a higher volume.

**Comment by z3ntu** [comment]
Hi, I don't think OpenRazer has anything to do with setting the volume of headphones, this should all happen via standard APIs over USB.
It's possible that Synapse on Windows uses a different way of setting it which could explain this behavior.

**Comment by arisviel** [comment]
It's really not the driver, but the internal API. So far I have solved the problem by connecting via 3.5 jack
