### ISSUE TITLE
Create a flatpak the RazerGenie

### ISSUE THREAD

**Issue by LeandroStanger** [z3ntu/RazerGenie#12]

**Comment by z3ntu** [comment]
I have a relatively well working version of RazerGenie on the branch `flatpak`. Maybe the appstream metadata needs some work but otherwise I think it's okay.
Maybe if you did more with flatpak than I (which you apparently did) you can look over the flatpak json and the appstream xml.

**Comment by LeandroStanger** [comment]
Will you create it on [flathub](https://github.com/GouveaHeitor/nipe/issues/flathub.org)?

**Comment by z3ntu** [comment]
Yes that is the plan.

**Comment by z3ntu** [comment]
https://github.com/flathub/xyz.z3ntu.razergenie :+1:
