### ISSUE TITLE
Keymapping support for Tartarus?

### ISSUE THREAD

**Issue by KayTaneJupiter** [z3ntu/RazerGenie#120]
Keymapping support for Tartarus?

**Comment by z3ntu** [comment]
Hi, can you please try this software to see if it works for you? https://github.com/sezanzeb/key-mapper

**Comment by KayTaneJupiter** [comment]
Looks like key-mapper can do it. Thanks.

**Comment by z3ntu** [comment]
Perfect, closing this issue then.
