### ISSUE TITLE
No dark theme availible on the AUR-"razergenie" version?

### ISSUE THREAD

**Issue by 95111** [z3ntu/RazerGenie#121]
I see the screenshots on the README & around the internet that are in a dark theme. But I can't find button for it.
I looked at the preferences (Only valid option is "Download device images"). My system standard-theme is dark, too.

I have the following versions (should be the latest): deamon (3.0.1) & RazerGenie (0.9.0) running on Arch Linux.

**Comment by z3ntu** [comment]
The screenshot in the README is made with the Breeze Dark theme. It is a standard Qt application so if you have a dark theme set for Qt, then it should work properly.
What desktop environment are you using?

**Comment by 95111** [comment]
I'm using Gnome. Is it possible to get a dark theme withozt the specific Breeze Dark theme?

**Comment by z3ntu** [comment]
You can search the internet how to "set a dark theme for Qt applications on GNOME", should be fairly easy to find. I don't use GNOME myself so I can't help you with first-hand experience.

**Comment by 95111** [comment]
Found it. Thx for the help
