### ISSUE TITLE
Razer Huntsman Elite

### ISSUE THREAD

**Issue by ghost** [z3ntu/RazerGenie#124]
Hi there i downloaded the ppa's stable branch and install the razer genine app but i am getting a problem with the razer genie not recognising my keyboard to programme it the Huntsman Elite. 
throw up an unknown matrix dimensions of matrix dimens: 9 22, and it says in the information the my keyboard layout of (en_GB)
is not supported yet. the daemon version is 3.1.0 my firmware version is v1.4 
can you please add my keyboardlayout of (en_GB) to the update of the daemon.
thanks
william

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
