### ISSUE TITLE
No lrelease?

### ISSUE THREAD

**Issue by him5** [z3ntu/RazerGenie#129]
![Screenshot 2022-01-03 7 05 38 AM](https://user-images.githubusercontent.com/50527029/147933867-2a2e6e9c-e047-4c88-a85c-f7bf0fe47a46.png)

**Comment by him5** [comment]
https://gist.github.com/him5/00a87b861a6bd14e147c571f26cbb62e

**Comment by z3ntu** [comment]
lrelease is part of qt5-tools (or maybe called qt5-qttools or something else), to install that wherever you get your Qt5 from (looks like you're building on ChromeOS?)

**Comment by him5** [comment]
yeah

**Comment by Techwolf** [comment]
I encounter the same thing on my system. The fix I did was use cmake instead of meson.

**Comment by z3ntu** [comment]
Closing as it's not an issue with the app itself.
