### ISSUE TITLE
Device type: Mouse

### ISSUE THREAD

**Issue by kardebadas** [z3ntu/RazerGenie#13]
Razer Naga Hex V2 ( Bus 003 Device 003: ID 1532:0050 Razer USA, Ltd  )
Can you add the macros to this mouse?

**Comment by z3ntu** [comment]
I guess you got the title from the custom editor popup. The custom editor isn't for macros though but for setting the LEDs on your device manually. For that see #10 
If you really want macro support for the mouse, it's a different issue than the custom editor one.
Could you please clarify?

**Comment by z3ntu** [comment]
I'm closing this because this issue has not had recent activity.
