### ISSUE TITLE
Cli usage.

### ISSUE THREAD

**Issue by Unn4medUser** [z3ntu/RazerGenie#130]
Hello, 

First of all sorry because it's not realy an "issue" but i havent found how to use this software in cli. All the time i have a terminal open so its more quick for me to restore my configuration in cli. 

Does its possible to use it in cli or i shoud use a another software ? 

For exemple i want my keybord in `static #ff0000`
In `razergenie --help-all` i havent undestand how to do it quicly

Best regards.

**Comment by z3ntu** [comment]
This is not possible with RazerGenie. I think polychromatic has some kind of CLI interface but it's also mainly a GUI tool. We do have a Python API that you could also use to write your own scripts / CLI tool.

**Comment by Unn4medUser** [comment]
@z3ntu Ok, thank you very mutch. 

> We do have a Python API that you could also use to write your own scripts / CLI tool
Very nice i gona try if i can do something.

There is no problem to have RazerGenie and [razer-cli](https://github.com/LoLei/razer-cli) installed on the same computer ? 
Maybe a cli usage can be a next feature ?

Thank's for your help and best regards.
