### ISSUE TITLE
No en_GB support for Razer Blackwidow Chroma V3

### ISSUE THREAD

**Issue by Dominic-Hoe** [z3ntu/RazerGenie#132]
Hi there!

After installing OpenRazer and then RazerGenie, I discovered that my keyboard is not actually supported by RazerGenie's custom editor.

The output of `cat /sys/bus/hid/drivers/razerkbd/0*/kbd_layout`, as suggested by the OpenRazer wiki, is `06`.

I have attached a picture of my keyboard below.
![IMG_3919](https://user-images.githubusercontent.com/78672762/153074883-98451153-2eba-4ba9-beb0-828721f8bd7e.jpg)

(I'm aware it needs a good dusting 😂)

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!

**Comment by mattiusclay** [comment]
Different keyboard to OP, same problem. Using 1.0.0 and keys still aren't lining up properly. The custom layout is showing M (macro) keys on the left but the my Huntsman v2 UK doesn't have them.

**Comment by z3ntu** [comment]
@mattiusclay Please open a new issue for this, let's not mix up different things.
