### ISSUE TITLE
error building current git (qt5-compile-de.ts)

### ISSUE THREAD

**Issue by ShalokShalom** [z3ntu/RazerGenie#135]
Hi there

I get this error message, when I try to build the current git https://github.com/z3ntu/RazerGenie/commit/fa4e466caddb652552da3c065f9dafa8d56fd37a
```

ERROR: Target 'qt5-compile-de.ts' has 1 outputs: ['de.qm'], but only 29 "install_dir"s were found.
Pass 'false' for outputs that should not be installed and 'true' for
using the default installation directory for an output.
```

Log: https://paste.ee/p/TJCMa

**Comment by ShalokShalom** [comment]
Related to: https://github.com/mesonbuild/meson/issues/10301

**Comment by z3ntu** [comment]
Yep, you found the correct issue :)
