### ISSUE TITLE
[Feature Request] Change polling rate via CLI

### ISSUE THREAD

**Issue by RustyReich** [z3ntu/RazerGenie#138]
I have a mouse with a maximum polling rate of 1000hz which is what I keep it at most of the time. However, there are a few older games I play that have issues with high polling rates, and so I have to lower to 125hz to play them enjoyably. It would be really nice if I could set keyboard shortcuts to run commands such as `razergenie -poll_rate 125` or something of the sort, so that I didn't have to physically open the application each time in order to change the rate.

**Comment by z3ntu** [comment]
You can use [polychromatic-cli](https://github.com/polychromatic/polychromatic/blob/master/polychromatic-cli) from polychromatic or [razer-cli](https://github.com/LoLei/razer-cli) for CLI access. I don't plan on adding CLI functionality to RazerGenie as it'd essentially duplicate those two projects.
