### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by DafelixCly** [z3ntu/RazerGenie#139]
I have a Razer mouse, a Basilisk v3 and I'm using arch.
It was working perfect untill 2 or 3 days ago. Now it detects the mouse, but changing the DPI or RGB settings does nothing on the actual mouse.

**Comment by DafelixCly** [comment]
I figured it out.
The thing is that this mouse have 5 presets saved on memory. I didn't notice at first, but apparently Razergenie only works with the default one. It would be nice if it worked with the other 4 presets, but I'm fine with just one working.

**Comment by z3ntu** [comment]
Can you give any details on that? I'm not too familiar with presets feature.

**Comment by z3ntu** [comment]
Weird, can you open an issue in the openrazer repo for this detailing this behavior? If you want to be sure you can also try polychromatic which is a different frontend than RazerGenie but I doubt this would change anything.

**Comment by DafelixCly** [comment]
Like I said, since I now know that the problem is with the selected preset, I don't really have a problem at all. Also, I just can't get polychromatic to work on my PC, so for now I will just use a VM to change settings on Synapse and live with it.
Thank you for everything.
