### ISSUE TITLE
Custom Editor does not work after update 

### ISSUE THREAD

**Issue by wemmsi** [z3ntu/RazerGenie#14]
Hello!
I've updated to the latest version (0.7) today, but since then the custom editor does not open anymore.
I just get a message with "Your keyboard layout (error) is not yet supported by RazerGenie. Please open an issue in the RazerGenie repository".
My keyboard is the Razer Ornata Chroma, which is correctly showing up as an device in RazerGenie. 
Also I can select the effects like "wave", etc.
Thanks and kind regards!

**Comment by z3ntu** [comment]
Yep, there seems to be an issue with the latest openrazer version.
Does `/sys/bus/hid/drivers/razerkbd/0*/kbd_layout` exist and if yes, what does it output when you `cat` the file?

**Comment by wemmsi** [comment]
The file kbd_layout does not exist.
Sure, I will reinstall the package and write again!

**Comment by z3ntu** [comment]
Please follow https://github.com/polychromatic/polychromatic/issues/146#issuecomment-379465409

**Comment by wemmsi** [comment]
I followed the instructions on the comment you linked, but now either polychromatic or razergenie open anymore.
I tried to reinstall razergenie, but it fails because now I get configuration errors via dpkg:
$ sudo dpkg -i razergenie_0.7-1_amd64.deb 
Vormals nicht ausgewähltes Paket razergenie wird gewählt.
(Lese Datenbank ... 257453 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von razergenie_0.7-1_amd64.deb ...
Entpacken von razergenie (0.7-1) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von razergenie:
 razergenie hängt ab von libqt5core5a (>= 5.6.0~beta); aber:
  Version von libqt5core5a:amd64 auf dem System ist 5.5.1+dfsg-16ubuntu7.5.

dpkg: Fehler beim Bearbeiten des Paketes razergenie (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für libc-bin (2.23-0ubuntu10) werden verarbeitet ...
Trigger für gnome-menus (3.13.3-6ubuntu3.1) werden verarbeitet ...
Trigger für desktop-file-utils (0.22-1ubuntu5.1) werden verarbeitet ...
Trigger für mime-support (3.59ubuntu1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.15-0ubuntu1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 razergenie

If I try to install a newer version of libqt5core5a, it also fails because a lot dependencies would need to be updated.
The official newest (supported) version is 5.5.1+dfsg-16ubuntu7.

**Comment by wemmsi** [comment]
Never mind, I fixed it now!
Thank you!
