### ISSUE TITLE
Create a snap package 

### ISSUE THREAD

**Issue by heidiwenger** [z3ntu/RazerGenie#140]
For an easy installation, clicking "Install" at Snap Store in Ubuntu, which is the first Linux distro for many new users now coming to Linux. Solus, KDE Neon, Manjaro, MakuluLinux, Ubuntu MATE etc. support snapd by default too.

As i read here, many seemed to end up in the world of pain trying to install RazerGenie. Maybe it is time to attempt a creation of a simple package with all dependencies and in secure sandbox? I mean, why not aim for a simple user friendly way to install on Linux? A snap package also enables an easy roll back or a version in case of need. 

Every single part of Snap that you come into contact with is open source. The package format, the daemon, the website (snapcraft.io), and the Snap Store that runs on your system. 

The only part that is not is some piece of the backend on Ubuntu's servers.

Could a snap package by any chance be possible then? A simple one click install, that is. Thanks.

**Comment by z3ntu** [comment]
There's already a flatpak for RazerGenie and I'm personally not interested in snap.

Also note, that when installing the flatpak (same situation would be for snap) you still need to install openrazer as normal via distribution package because of kernel modules and everything. So it'll never be a one-click install no matter what the frontends do.

**Comment by heidiwenger** [comment]
> There's already a flatpak for RazerGenie and I'm personally not interested in snap.
> 
> Also note, that when installing the flatpak (same situation would be for snap) you still need to install openrazer as normal via distribution package because of kernel modules and everything. So it'll never be a one-click install no matter what the frontends do.

Oh, that sounds kinda awkward. So there is no possibility to make this software a one click install ever? It is a total impossibility? :/

**Comment by z3ntu** [comment]
Unless there's a total rewrite of openrazer which doesn't need kernel modules anymore, no.
