### ISSUE TITLE
Device Type not implemented (Tartarus V2)

### ISSUE THREAD

**Issue by ChalicerK** [z3ntu/RazerGenie#141]
Hi
I got the message - please open an issue in the repo.
The device name is: keypad

**Comment by someren76** [comment]
Same here.

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!

**Comment by ChalicerK** [comment]
Hi,
took me a while to verify. Works now - thanks :)
Looks like this:
![grafik](https://user-images.githubusercontent.com/115928466/209665247-2bff8c21-0788-4c75-92d2-eeea67d829bd.png)

**Comment by z3ntu** [comment]
Actually I'm interested in making a proper layout for this device. 

Since the device looks like this (please tell me if yours doesn't) https://assets2.razerzone.com/images/pnx.assets/eedda32401e1dfd06b3de23f8eda8685/razer-tartarus-v2-hero-mobile.jpg , I'm guessing the left five rows lights up the light under each key but what does the last column 0:5 to 3:5 do?

**Comment by ChalicerK** [comment]
My guess is that those are mousewheel and the keymaps (maybe).
The cursor has no backlight.

I needed to re-install windows on a another drive to get razer synapse working over there. Then I needed to install synapse 2 times to get all devices recognized. But finally I was able to make these screenshots.

![lighting](https://user-images.githubusercontent.com/115928466/210076237-da362a65-dbbf-4020-905c-d907e1b74efc.png)
![no_selection](https://user-images.githubusercontent.com/115928466/210076260-28f1c55c-fcf0-4fd2-a4ac-c97c0ef5d96a.png)

**Comment by ChalicerK** [comment]
How did you start working with openrazer ? I wanted to check the documentation myself to see if I can send a config file to adjust the key mappings. The only thing I found so far is the wiki https://github.com/openrazer/openrazer/wiki

**Comment by z3ntu** [comment]
The key mapping can be done independent of OpenRazer with https://github.com/sezanzeb/input-remapper

What I was asking you is which lights the different buttons in the UI (what you posted in https://github.com/z3ntu/RazerGenie/issues/141#issuecomment-1365860760) control on your Tartarus. Then I can assign names and make it pretty so it looks sort of like [this from the readme](https://camo.githubusercontent.com/1f957d96be7c151a06125022a74e0d5d1c12420af3cbcf6ac239ddb398ed670e/68747470733a2f2f7a336e74752e6769746875622e696f2f52617a657247656e69652f73637265656e73686f74732f637573746f6d656469746f722e706e67) (obviously quite different for Tartarus)

**Comment by ChalicerK** [comment]
<google-sheets-html-origin><style type="text/css"></style>

01 | 0:0 | 02 | 0:1 | 03 | 0:2 | 04 | 0:3 | 05 | 0:4
06 | 1:0 | 07 | 1:1 | 08 | 1:2 | 09 | 1:3 | 10 | 1:4
11 | 2:0 | 12 | 2:1 | 13 | 2:2 | 14 | 2:3 | 15 | 2:4
16 | 3:0 | 17 | 3:1 | 18 | 3:2 | 19 | 3:3 | Mousewheel | 3:4
  |   |   |   |   |   |   |   | 20 | 3:5
No effect |   |   |   |   |   |   |   |   |  
0:5 |   |   |   |   |   |   |   |   |  
1:5 |   |   |   |   |   |   |   |   |  
2:5 |   |   |   |   |   |   |   |   |

**Comment by z3ntu** [comment]
Please try #150 if that works for Tartarus V2. Please comment there for any testing results.

For Firefly V2 yes, please open a new issue.

**Comment by ChalicerK** [comment]
hi - tested this one as well. The layout is working but the razerkeypad6.json seemed to be missing in the build script - following the firefly issue.
- as described earlier the changes in color only seem to get applied when I change the last row - 16,17,18,19 Wheel and 20

**Comment by z3ntu** [comment]
At most I could imagine that the firmware on the device is sorta broken and only updates the previous ones when it has got the last one - normally Synapse sends all rows after each other even when only something in one row was changed. Could you create an issue for this in OpenRazer (if one doesn't already exist) and we can look into a workaround there? 

But thanks for testing, let's merge the UI changes :)
