### ISSUE TITLE
Your keyboard layout (Nordic) is not yet supported by RazerGenie for this keyboard. (Huntsman V2 TKL)

### ISSUE THREAD

**Issue by jpalko** [z3ntu/RazerGenie#145]
I noticed that my keyboard has been added as a supported keyboard to openrazer with v3.5 and tried to do custom edit to the keyboard with RazerGenie and got:
Please open an issue in the RazerGenie repository. Device name: Razer Huntsman V2 Tenkeyless - matrix dimens: 6 18

Your keyboard layout (Nordic) is not yet supported by RazerGenie for this keyboard. Please open an issue in the RazerGenie repository.

Neither one of these layouts was found in the layout file: de_DE, en_US, en_GB. Exiting.

Here is a picture of my keyboard.
![image](https://user-images.githubusercontent.com/4025691/203026235-5197e290-f549-4854-a39d-0e17ae6d6a66.png)

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!

**Comment by jpalko** [comment]
Hi,

It does enable me to start editing but naturally the keys don't quite match the keyboard in the default fallback layout.
![image](https://user-images.githubusercontent.com/4025691/208063024-71080973-7f99-4554-825a-9ccabec31896.png)
![image](https://user-images.githubusercontent.com/4025691/208063061-fb3a3850-1950-4683-8648-1d72388302f3.png)
Interesting editing to be done. I'm guessing that this is just due to differences of the default fallback layout and what the keys are in my localized keyboard?

**Comment by z3ntu** [comment]
If you want to try, you can edit the layout file yourself, copying one part of the file `razerdefault18.json`, US or German, label that "Nordic" and adjust the keys where necessary. It should be picked up as soon as you re-open the custom editor. See also https://github.com/z3ntu/RazerGenie/wiki/Keyboard-layout-files for more info
