### ISSUE TITLE
Cannot "Open custom editor" for Razer Huntsman V2 Tenkeyless

### ISSUE THREAD

**Issue by deafpolygon** [z3ntu/RazerGenie#146]
Clicking "Open custom editor results in 3 pop-ups, and the lights turning off.  Changing the lighting to something else reactivates the lighting on the keyboard.   I am also using a  Razer Naga X.

- Please open an issue in the RazerGenie repository. Device name: Razer Huntsman V2 Tenkeyless - matrix dimens: 6 18
- Your keyboard layout (en_US) is not yet supported by RazerGenie for this keyboard. Please open an issue in the RazerGenie repository.
- Neither one of these layouts was found in the layout file: de_DE, en_US, en_GB. Exiting.

Attempting to do the same with the mouse gives this popup. 

- Please open an issue in the RazerGenie repository. Device type: mouse

Edit:  Added a note about the mouse.
```
Operating System: Fedora Linux 37
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 6.0.9-300.fc37.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT
Manufacturer: ASUS
```

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
