### ISSUE TITLE
Razer BlackWidow Chroma british keyboard layout not supported

### ISSUE THREAD

**Issue by 00Asgaroth00** [z3ntu/RazerGenie#15]
Hi,

Would it be possible to add support for the Razer Blackwidow Chroma in RazerGenie. I am presented with the following error/info screen when I try to click on the "Open custom editor" button for the Keyboard:

![razergenie](https://user-images.githubusercontent.com/13218073/38457436-26e877e0-3a88-11e8-871f-8a1094cb944a.png)

I'm not sure if I have not configured something correctly, but any assistance would be appreciated. For info, my keyboard layour is UK for this keyboard.

**Comment by z3ntu** [comment]
Please follow https://github.com/polychromatic/polychromatic/issues/146#issuecomment-379465409

**Comment by 00Asgaroth00** [comment]
Hi, I have just downgraded to version 2.2.2 of the driver so that I can test out the Razer Naga Epic Chroma mouse driver. If I follow the steps in that comment then I will be upgrading to version 2.3.0 again. Although, come to think of it, The BlackWidow and Kraken driver may still be that from v2.3.0 as I have not rebooted the system since downgrading to v2.2.2

**Comment by 00Asgaroth00** [comment]
OK, followed the steps below to reinstall openrazor (adaped from the comment you mentioned above), but I am still getting the error described in the initial post.

As the root user:

```
apt purge *openrazer*
ls /usr/src/
rm -rf /usr/src/openrazer-driver-1.0.0
dpkg -i dist/*.deb
apt install -f
```

The last two steps are the installation of the debs that are created with the "feature_nagaepicchroma_0x003e" feature branch of openrazer.

I then rebooted the system, however, the issue still persists.

**Comment by z3ntu** [comment]
Can you start RazerGenie from a terminal and give me the output when opening the custom editor?

**Comment by 00Asgaroth00** [comment]
Hi,

Here is the output:

```
~$ razergenie 
librazer: There was an error in QString librazer::QDBusMessageToString(const QDBusMessage&) !
librazer: "org.freedesktop.DBus.Error.UnknownMethod"
librazer: "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/dbus/service.py\", line 654, in _message_cb\n    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)\n  File \"/usr/lib/python3/dist-packages/dbus/service.py\", line 246, in _method_lookup\n    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))\ndbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getKeyboardLayout is not a valid method of interface razer.device.misc\n"
```

**Comment by z3ntu** [comment]
Ah yeah. That's because RazerGenie 0.7 requires OpenRazer version 2.3.0 or higher. I'll rebase the `feature_nagaepicchroma_0x003e` branch for you so you can have the features of 2.3.0 :)

**Comment by 00Asgaroth00** [comment]
Hi, thanks for re-basing on v2.3. I have updated to your new version now, however, I still get the message popup when I click the custom editor button, only, this time, it actually shows my keyboard layout (previously it did not), screenshot below:

![razergenie_en_gb](https://user-images.githubusercontent.com/13218073/38549219-77cebc12-3cab-11e8-978c-e633add2a108.png)

**Comment by z3ntu** [comment]
Ah yeah that's better :)
Can you make a photo of your keyboard so the keys are visible on it? I will make a layout then.

**Comment by 00Asgaroth00** [comment]
Hi, here's a picture, excuse the dirty keyboard though :)

![razerblackwidowchroma_](https://user-images.githubusercontent.com/13218073/38556013-153dc182-3cc0-11e8-9d8b-fc4293873cd8.jpg)

**Comment by 00Asgaroth00** [comment]
OK, I've downloaded the definition now, and the button now works, I'll need to play with it over the comming days to confirm that all is loking okay.
I dont think I've ever used the ¬ button before, except for this email, but that particular button also has the ` (back tick) symbol and | (pipe) symbol on it, I use both frequently while scripting.

**Comment by z3ntu** [comment]
bump?

**Comment by 00Asgaroth00** [comment]
Hi, I've not have a chance to play with the custom editor yet, however, if I wanted to make improvements to the layout image, is there a tutorial somewhere that can show me how to do it?

**Comment by z3ntu** [comment]
It's a json file located at https://github.com/z3ntu/RazerGenie/blob/en_GB-kbd-layout/data/matrix_layouts/razerdefault22.json that you will have to edit manually.

**Comment by z3ntu** [comment]
bump
