### ISSUE TITLE
Firefly V2 custom Editor

### ISSUE THREAD

**Issue by ChalicerK** [z3ntu/RazerGenie#151]
Hi,
the custom editor for the Firefly V2 shows the following:
![image](https://user-images.githubusercontent.com/115928466/213179686-121e4263-60d2-420d-838c-2a1dfe7cb5b5.png)

looking at the lights it should be like this:
![image](https://user-images.githubusercontent.com/115928466/213181539-d88a4e0d-a91a-4c8a-8609-84a9bb61d79c.png)

Thanks

**Comment by z3ntu** [comment]
![image](https://user-images.githubusercontent.com/3768500/213874445-00c9ffa0-5a7f-48e7-a776-8e693efbcd17.png)

Please test #152 to verify :)

**Comment by ChalicerK** [comment]
Hi, has been a while.
I tried to figure out how to test branches.
My idea was to use pamac to build the git version and then change the build script from
('git+https://github.com/z3ntu/RazerGenie.git')
to 
('~/repos/RazerGenie') where I had cloned the firefly_v2_layout branch into ... it did not work.
I was looking at the documentation of pamac but it only is talking about basics - https://wiki.manjaro.org/index.php?title=Pamac

Is the idea to use meson to build it locally without the help of pamac?
Or is there an easier/smarter way.

**Comment by ChalicerK** [comment]
mhhh some success ... 'git+https://github.com/z3ntu/RazerGenie.git#branch=firefly_v2_layout' at least did not fail. It tells me the razermousepad19.json is not found ...

**Comment by ChalicerK** [comment]
I copied the the file to /usr/share/razergenie/matrix_layouts by hand - after the file was there I can confirm it's working :)

**Comment by z3ntu** [comment]
Thanks for trying! It wasn't your fault it didn't work ootb, I forgot to add the new json file to the build script. Just fixed that :)
