### ISSUE TITLE
Razer DeathAdder V3 Pro has other ID and won't recognize

### ISSUE THREAD

**Issue by r3lax3rs** [z3ntu/RazerGenie#153]
Hello,

As i can see on supported devices for RazerGenie it says:
Razer DeathAdder V3 Pro (Wired) | 1532:00B6
Razer DeathAdder V3 Pro (Wireless) | 1532:00B7

Funny thing is that when my mouse is wired it is recognized within RazerGenie, and according to my system 00B6.
But when I go wireless it says 1532:00B3 and is not recognized by RazerGenie. I think because of the ID.
Is there an easy way to fix this?

 lsusb -d 1532: -v

Bus 001 Device 018: ID 1532:00b3 Razer USA, Ltd Razer HyperPolling Wireless Dongle
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00b3 
  bcdDevice            1.01
  iManufacturer           1 Razer
  iProduct                2 Razer HyperPolling Wireless Dongle
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              2 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      0 
      iInterface              2 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     260
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               4
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              2 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      63
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               4

![image](https://user-images.githubusercontent.com/124855911/217714862-6e5fd027-5874-425e-a101-b9749fda40c5.png)
Wireless

![image](https://user-images.githubusercontent.com/124855911/217714945-049134b6-a93c-461d-b8c8-6251b89762c6.png)
Wired

**Comment by z3ntu** [comment]
See https://github.com/openrazer/openrazer/issues/1869 . You can also test the open PR for this device: https://github.com/openrazer/openrazer/pull/1921

**Comment by r3lax3rs** [comment]
Hello z3ntu,

I also came across those threads. #1869 they mention how to pair / unpair. Which ive tried replacing b7 with b3 but no result.
echo b3 > /sys/module/razermouse/drivers/hid:razermouse/*/hyperpolling_wireless_dongle_pair
bash: /sys/module/razermouse/drivers/hid:razermouse/*/hyperpolling_wireless_dongle_pair: No such file or directory

Yet as you can see, it is running and detecting it while wired.
My mouse does work wireless aswell, as that's how I mainly use it. It;s just not recognized by RazerGenie so I can adjust hz.
I do have to mention that I didn't had to do anything to make it work like pairing. When I installed Linux Ubuntu 22.04 on a new NVMe and booted it up, it worked wireless right away.

In #1869 they are talking about the b3 thing and that it supports it. When checking Commits and the readme.md it tells me they indeed added the hyperdongle 1532:00B3.
I have no idea how to use this since I am really new to using Linux & Github. I was happy when after some time searching I could get openrazer to work with the whole MOK thing but I have no clue what do here to make use of this open PR. Could you hint me in the right direction to make this work?
As far as I can see they make use of .py files which I assume is Python? Yet I have little experience with it from years ago at school, and don't see any guide as to how to use this or how make use of all these files to make it work.

Also in #1889 they talk about Wireless but it is all addressed with b7 for wireless. (Which I assume is the default dongle?)
I haven't tried but i can imagine the default dongle would be this b7 value and the hyperdongle is the b3 value.

Thanks for your time :)

**Comment by z3ntu** [comment]
Are you sure you installed the version based on the PR correctly? Try `find /sys -name hyperpolling_wireless_dongle_pair`

**Comment by BLooD-DoG** [comment]
Yeah, the hyperpolling wireless dongle isn't part of the DeathAdder V3 Pro. It's an optional dongle that gives you up higher polling rates than the mouse and including wireless dongle support on their own.

The dongle is a separate device and it supports several mice (Viper V2 Pro, Basilisk V3 Pro, possibly others).

So, you need to wait until support for this dongle is included in openrazer, or try the PR that z3ntu mentioned which includes support.

**Comment by r3lax3rs** [comment]
Thanks for helping. Sorry for the late reaction, was too busy playing Hogwarts Legacy.

@z3ntu I have no idea. When i put in your command I get:
find /sys -name hyperpolling_wireless_dongle_pair
find: ‘/sys/kernel/tracing’: Permission denied
find: ‘/sys/kernel/debug’: Permission denied
find: ‘/sys/fs/pstore’: Permission denied
find: ‘/sys/fs/bpf’: Permission denied

Funny thing is, I installed Osu! and you can see raw input in the menu. When moving my mouse it gives me 4000 reports back. Which is weird because it doesn't get recognized within RazerGenie.
![image](https://user-images.githubusercontent.com/124855911/219500105-8a9901f4-221a-4c0a-8a82-53d95224e944.png)

The only thing then would be that I can't select DPI. But it doesn't feel like a different DPI from what I've chosen wired so there's that.

I have no idea how to install the PR. I saw .py files which are for Python right? I have almost no knowledge with Python so I'd probably have to look into that then. Else I'd probably have to wait for the support to be included.
Anyways thanks for your help.

**Comment by z3ntu** [comment]
https://github.com/openrazer/openrazer/wiki/Building-a-package

**Comment by r3lax3rs** [comment]
I never tried this but i'm going to give this a try soon. Thanks!
