### ISSUE TITLE
Turn off on Screensaver reseting

### ISSUE THREAD

**Issue by ChalicerK** [z3ntu/RazerGenie#157]
Hi,
I always need to check the box on the lower right end "Turn off on Screensaver" or "Beleuchtung bei Bildschirmschoner abdrehen" (in the German translation).

I see in the RazerGenie.conf
```
    backend=OpenRazer
    downloadImages=true
```

Are there any other configurations I could set in that config file?

**Comment by z3ntu** [comment]
I believe this setting should be persisted on the openrazer side, RazerGenie shouldn't touch anything by default there. Check `devices_off_on_screensaver` in `~/.config/openrazer/razer.conf`

**Comment by ChalicerK** [comment]
thanks - I wasn't aware of that. I can confirm it worked that way. 
A hint in RazerGenie would be nice - just to make it obvious.

**Comment by z3ntu** [comment]
Do you have an idea how to best present it in the UI? Or another way honestly could be to just make OpenRazer persist the setting of the user and not use the default from the config every time it launches. Let me know what you think.

**Comment by z3ntu** [comment]
Hi, checking again do you have any suggestions how to improve the UI there? Otherwise I'll be closing this issue :)

**Comment by TriMoon** [comment]
@z3ntu 
I think the current display is adequate:
![image](https://github.com/z3ntu/RazerGenie/assets/1723378/03e4d13b-746e-4f15-b0a1-7803218ec8c9)

But i noticed that changing that checkbox, doesn't change anything in any config :thinking: 
Maybe the `devices_off_on_screensaver` setting should be updated when you change the checkbox state...

**Comment by z3ntu** [comment]
@TriMoon Opened #161 and #162 for your suggestions.

For the original issue reported here, closing it.
