### ISSUE TITLE
Ubuntu GPG keys expired

### ISSUE THREAD

**Issue by vegaman** [z3ntu/RazerGenie#158]
Sorry if you don't maintain the apt repos. But the GPG keys linked for the Ubuntu repos on https://software.opensuse.org/download.html?project=hardware%3Arazer&package=razergenie have expired.
The keys linked on the Debian page are still valid and match the key used on the Ubuntu repos though.

**Comment by z3ntu** [comment]
Trigger a rebuild in the OBS web interface, now they seem to be valid until 2025 again. Thanks for letting me know!
