### ISSUE TITLE
Didn't detected Blade 15 (2019) Advanced

### ISSUE THREAD

**Issue by chenelias** [z3ntu/RazerGenie#159]
After I install openrazer and RazerGenie on my razer blade 15 2019 advanced latop, RazerGenie shows No device detected.

How can I fix that?

**Comment by z3ntu** [comment]
Did you already check https://github.com/openrazer/openrazer/wiki/Troubleshooting?

**Comment by chenelias** [comment]
Hey, I check it before.
I just forgot to reboot my latop, now it work well.
Thanks!!!
