### ISSUE TITLE
Hue lights sync?

### ISSUE THREAD

**Issue by y4my4my4m** [z3ntu/RazerGenie#16]
Hi, sorry if this is an inappropriate question.
I've just been looking at the code and was wondering it if would be relatively easy to add Hue lights sync with the chroma keyboard. I've noticed part of the code is in C++, is it still possible to add such features working only with the Python end of the code?

Thank you

**Comment by z3ntu** [comment]
It's probably possible and you'll be interested in the pylib we created for openrazer (the package is called python3-openrazer or similar, depends on the distribution).
Several examples are available at https://github.com/openrazer/openrazer/tree/master/examples (we unfortunately have no formal documentation for it yet).
If you have any further questions, you can also join our community chat, either via Telegram (https://t.me/joinchat/A1E4RT9TxhnxyetdQCSj7Q) or via Matrix (https://matrix.to/#/#openrazer:matrix.org)

**Comment by y4my4my4m** [comment]
@z3ntu Thank you!

I will do so :)
