### ISSUE TITLE
Nommo v2

### ISSUE THREAD

**Issue by ChalicerK** [z3ntu/RazerGenie#166]
Hi,
just installed the Nommo v2 and it did not show up in razergenie.

I was looking through another post here and executed the python script mentioned in there:
`python3 -c "from openrazer.client import DeviceManager; a = DeviceManager(); print(a.devices)"`

The speakers don't show up.
~~I restarted my PC because I did not figured out how to restart the razer daemon~~
I also restarted the daemon

I see the speakers as a device in general and they work: 
usb1-1\x2d10-1\x2d10:1.1-sound-card3-controlC3.device         loaded active plugged   Razer_Nommo_V2

Sound is working but no way to configure the lights.

When I checked [openrazer](https://openrazer.github.io/) I can see Nommo Chroma as supported, but no idea if that includes the v2 ... is there any way how I can debug this or get in contact with the openrazer team?
Help would be much appreciated.

Thanks in advance

**Comment by z3ntu** [comment]
The device is not supported yet in OpenRazer, see https://github.com/openrazer/openrazer/issues/2172. Nothing to do on RazerGenie side for this.

**Comment by ChalicerK** [comment]
Thank you very much for the info!
