### ISSUE TITLE
Razer BlackWidow Classic unable to see Custom Editor Button

### ISSUE THREAD

**Issue by alcomposer** [z3ntu/RazerGenie#17]
Installed RazerGenie on Arch Linux, I am unable to see Custom Editor button when device is selected. Changing logo brigtness with slider works.

![razergenie_no_editor](https://user-images.githubusercontent.com/12004932/39808404-fd45a7a6-53bd-11e8-95af-b7ff06df9fd9.png)

**Comment by z3ntu** [comment]
That device does not support setting a custom value per key. Nothing I can do about that unfortunately

**Comment by alcomposer** [comment]
Thanks @z3ntu.  I couldn't find any information regarding models and capabilities. (Apart from driver working or not). Is there a documentation page which lists which models do support custom values etc?

**Comment by z3ntu** [comment]
Not exactly but you can go through either the daemon source (Ctrl+F for `METHODS = ` in one of the files in https://github.com/openrazer/openrazer/tree/master/daemon/openrazer_daemon/hardware (except `device_base.py` and `__init__.py`) or in the driver source (look for the section with a bunch of `CREATE_DEVICE_FILE` statements in the `*.c` files in https://github.com/openrazer/openrazer/tree/master/driver and find the `case` statement for your device). Searching in the daemon code is easier :wink:
