### ISSUE TITLE
Can I also control my asus mobo and lian li fans?

### ISSUE THREAD

**Issue by Tech127x** [z3ntu/RazerGenie#170]
Is there a way I can import my Asus mobo, keyboard, and Lian Li Uni Fans so everything matches?

**Comment by z3ntu** [comment]
No, RazerGenie only interfaces with OpenRazer and OpenRazer is only targetting Razer (or very few 3rd but Razer-compatible) devices.

You maybe want to look at OpenRGB for your use case.
