### ISSUE TITLE
Razer Tartarus Pro

### ISSUE THREAD

**Issue by DrKlabauter** [z3ntu/RazerGenie#171]
I cannot see my Razer Tartarus Pro in RazerGenie. My Razer Basilisk V3 works without any problems. Both devices appear under lsusb | grep 1532.

**Comment by z3ntu** [comment]
Hi, the Tartarus Pro is unfortunately not yet supported in OpenRazer, see https://github.com/openrazer/openrazer/issues/1039

There's an open pull request from two years ago https://github.com/openrazer/openrazer/pull/1817 but it was never finished (and is not working to my knowledge), my last comment there from March has a link to how you could take a shot at fixing it.
