### ISSUE TITLE
Where do I get libopenrazer0 ?

### ISSUE THREAD

**Issue by aaronjolson** [z3ntu/RazerGenie#172]
Trying to install razergenie.
I installed openrazer-meta already. I also installed libqt5widgets5 libqt5xml5
I am stuck on this last dependency error
```
sudo dpkg -i razergenie_1.1.0-0_amd64.deb
Selecting previously unselected package razergenie.
(Reading database ... 226985 files and directories currently installed.)
Preparing to unpack razergenie_1.1.0-0_amd64.deb ...
Unpacking razergenie (1.1.0-0) ...
dpkg: dependency problems prevent configuration of razergenie:
 razergenie depends on libopenrazer0 (>= 0.2.0); however:
  Package libopenrazer0 is not installed.

dpkg: error processing package razergenie (--install):
```

How do I resolve this?

**Comment by z3ntu** [comment]
Add the apt repository like is written in the installation instructions and don't try to install the deb file manually, then it can also pull in the libopenrazer package.

**Comment by aaronjolson** [comment]
Ah, that makes sense, thank you!

**Comment by z3ntu** [comment]
Unfortunately there's no way to customize the downloads page on the opensuse.org domain (I use the OpenSuse Build Service (OBS) to build my packages for various distributions).

I could probably replicate them - or the good parts at least - on my own but then I also need to maintain it for any changes or any new distribution versions for example.

So not your fault that it's not clear what to do ;)

**Comment by SystemParadox** [comment]
> Add the apt repository like is written in the installation instructions

I added the openrazer repository already but I'm still having this issue. I'm not seeing any mention of an apt repository for razergenie. Am I missing something?

**Comment by z3ntu** [comment]
@SystemParadox Please don't pile onto already solved issues. Please open a new one.
