### ISSUE TITLE
Doesn't work in the presence of systemd but with a different init in use

### ISSUE THREAD

**Issue by dsalt** [z3ntu/RazerGenie#2]
`Failed to get properties: Process org.freedesktop.systemd1 exited with status 1`

May be partly to do with changes in openrazer…

**Comment by dsalt** [comment]
Looks like local breakage. Ignore.

**Comment by z3ntu** [comment]
I actually wrote checks especially for systems without systemd, so distros like Gentoo or Alpine can use it without RazerGenie being weird :)
