### ISSUE TITLE
Keyboard layout (fr_FR) not supported

### ISSUE THREAD

**Issue by Mathux** [z3ntu/RazerGenie#21]
Hi,
Would it be possible to add support for the keyboard of the Razer Blade Stealth late 2017 fr. 
I have this error when I want to open the cutom editor: "Your keyboard layout (fr_FR) is not yet supported by RazerGenie for this keyboard. Please open an issue in the RazerGenie repository."

Thank you

**Comment by z3ntu** [comment]
Please send me a picture of the keyboard layout, so how it looks like on your laptop.

**Comment by Mathux** [comment]
![img_20180716_090227](https://user-images.githubusercontent.com/25257425/42760124-608d7944-88d7-11e8-8dee-f2b0e605c27b.jpg)

**Comment by shashanknimje** [comment]
@z3ntu I've got the same issue with my Razer Blade 15 2018 model.

![img_5400](https://user-images.githubusercontent.com/9880535/44773898-8eeffe80-ab26-11e8-9841-be3bc6c17be4.jpg)

**Comment by z3ntu** [comment]
@shashanknimje en_US is already in the master branch so you can run `sudo curl https://raw.githubusercontent.com/z3ntu/RazerGenie/master/data/matrix_layouts/razerblade16.json -o /usr/share/razergenie/matrix_layouts/razerblade16.json` and you should have the layout locally.

I should probably release a new version relatively soon as I have a couple of user-facing changes in master but not as much as in the releases before :) Maybe after adding the French layout.

**Comment by z3ntu** [comment]
@Mathux And you can run `sudo curl https://raw.githubusercontent.com/z3ntu/RazerGenie/fr_FR-kbd-layout/data/matrix_layouts/razerblade16.json -o /usr/share/razergenie/matrix_layouts/razerblade16.json` .
Please verify, that all keys light up the corresponding LED on the keyboard.

**Comment by shashanknimje** [comment]
Thanks @z3ntu! :) I will test this and report back.

**Comment by Mathux** [comment]
I just tested it works great :)  (all keys light up the corresponding LED on the keyboard)
Thank you very much !
