### ISSUE TITLE
RazerGenie Custom Editor not working

### ISSUE THREAD

**Issue by ariesoftroy** [z3ntu/RazerGenie#22]
Hi, 
I'm trying to get a Custom Color Set on Razer Blade Stealth with Chroma Keyboard, so I installed from OBS repositories openrazer-daemon openrazer-doc openrazer-kernel-modules-dkms openrazer-meta (version 2.3.1-1) and razergenie 0.7.1. When I run razergenie from terminal it recognize and does correctly all lightning effects both on logo and keyboard, but when I press Open Custom Editor Button it's displayed only Set, Clear, Clear All   Buttons and NO keyboard layout.
![1](https://user-images.githubusercontent.com/36190617/42952646-7ea20448-8b68-11e8-9f5e-3f8e0643060f.jpg)
Meanwhile in terminal::
![2](https://user-images.githubusercontent.com/36190617/42952708-993f0878-8b68-11e8-974f-57aaa5bc0189.jpg)

**Comment by z3ntu** [comment]
Hi, sorry for the lack of response. If this is still an issue please reopen.
