### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by 2E0PGS** [z3ntu/RazerGenie#23]
It would be great if there was documentation detailing the current intergrated feature list of stable and develop builds.

That would save me guessing what I should expect to be in the GUI without having to uninstall and reinstall versions and/or try other GUI razor control software to see how they stack up. Ideally I would look at a feature list and see which is the superior client for my needs.

**Comment by z3ntu** [comment]
What you see on the screenshots in the readme is available. Basically everything Synapse supports minus macro stuff and key remapping.
