### ISSUE TITLE
Layout for Razer Blade 15 (2018)

### ISSUE THREAD

**Issue by cockytrumpet** [z3ntu/RazerGenie#25]
I modified razerblade16.json to map correctly to the Razer Blade 2018.  Every key works.
[razerblade2018.5x16.en_us.txt](https://github.com/z3ntu/RazerGenie/files/2244037/razerblade2018.5x16.en_us.txt)

I tried to move the up arrow in the custom editor layout to match but it wasn't having it.
![razer-blade-15-top-view](https://user-images.githubusercontent.com/3034594/43442251-e31f6f0c-9449-11e8-8658-5769af3fb702.jpg)

Console output:
```
Translation loaded: false
"BY1824A45001347"
"Razer Blade 15 (2018)"
DeviceListWidget: Received errored signal!
DeviceListWidget: Reason: "Image download disabled"
DeviceListWidget: Long reason: "Image downloading is disabled. Visit the preferences to enable it."
"keyboard"
CURRENT LOCATION:  "0"
Brightness: 29.41
CURRENT LOCATION:  "1"
```

**Comment by z3ntu** [comment]
Well that destroys my view that the layout is the same for devices with the same Matrix dimensions. This will probably not be fixed very soon because it requires re-thinking of how the layouts should be handled.

**Comment by z3ntu** [comment]
Hi, is this still relevant in the latest release v1.0.0? I visually checked the layout and apart from the arrow keys being a bit different it seems to match the picture. I'm closing this but if you're still interested I'm happy to help get this implemented.
