### ISSUE TITLE
Settings not persistent, lost after reboot

### ISSUE THREAD

**Issue by APoniatowski** [z3ntu/RazerGenie#30]
Hi there,

there seems to be a problem with keeping the settings persistent.  LED settings are lost and the Turn off on screensaver setting is also lost and defaults to being enabled, which is quite annoying in the dark (black keyboard in the dark). Polling rate is defaulted to 500Hz as well.

Is there a way to make this permanent? like a quick workaround?  

I am using Manjaro KDE:

**Comment by z3ntu** [comment]
(This issue actually belongs into the openrazer repo) Some options can be modified under `~/.config/openrazer/razer.conf`, like the `devices_off_on_screensaver` option.
The rest is not possible unfortunately. I've been working on a rewrite of OpenRazer (that doesn't use kernel drivers / dkms, but hidraw on Linux) where it would be possible to implement this feature.
About the polling rate: I don't think OpenRazer modifies the polling rate without telling it to do so it's probably just that RazerGenie displays the default value because it doesn't know any better.

**Comment by APoniatowski** [comment]
aaaah okey dokey. Thanks for the info.  I will create a ticket on their repo. I hope they get around to fixing it... its annoying to adjust my settings every time I reboot or switch on my PC.

**Comment by germ** [comment]
Would it be possible to simply store the current custom configuration in storage and have a lightweight daemon load the settings at login? This would also give us persistence between editing sessions.

**Comment by APoniatowski** [comment]
https://github.com/openrazer/openrazer/issues/663#issuecomment-417848315

One can create a python script to do this for now, and create service that will wait for the openrazer daemon to start before running the script (thanks to systemd). A dirty little hack, but at least it'll work

**Comment by germ** [comment]
I'm in the process of adding in support for loading/writing persistent configs with razergenie, biggest stumbling block at the moment is I haven't done C++/QT in a nice long time. But it's getting there, give me a few days. I really love the idea of using JSON for configuration, damn near everything can parse it and you can always edit it by hand, or do templating or whatever. 

I'm still going over what info OpenRazer allows to be queried over Dbus and drafting up a decent schema for the thing, but basic loading/exporting works and I have a tray tool that's in the works for parsing configs and toggling stuff. Keyboards only at the moment, but it's coming. 

As it stands I'm looking at profiles as encompassing multiple devices so solarized.json might drive your keyboard, mouse, mug, whatever all from the same file. So it's coming!

**Comment by barabanus** [comment]
> I really love the idea of using JSON for configuration

@germ, for human readable configs the industrial standard is to use YAML instead of JSON.

**Comment by Tank-Missile** [comment]
Any updates on this?

**Comment by germ** [comment]
I had it more/less working, but I don't think I ever pushed the code.

I desoldered the switches on my Razer gear, designed my own QMK keyboard and never looked back though. So I don't really have hardware to get working on this again.

**Comment by codeman101** [comment]
I noticed a similar issue to this but it's not involving reboot. Mine refers to restarting the program. I think I'll make a new issue.

**Comment by lucascampelo** [comment]
I have the same problem after reboot. Have Mouse and Keyboard sync with Spectrum Lighting. After reboot the keyboard changes to Breath Single. I'm using Ubuntu 20.04.

**Comment by z3ntu** [comment]
This should be solved now since quite a few OpenRazer versions.

**Comment by elemag75** [comment]
2025 CachyOS still same issues.
