### ISSUE TITLE
Symbol lookup error when i try to open razergenie with terminal [BUG]

### ISSUE THREAD

**Issue by Arthurlalves** [z3ntu/RazerGenie#34]
When i try to open razergenie with terminal even with a desktop shortcut it does'nt launch it and the terminal returns me this error. It's related with thist lib 'libqt5core5a' but i don't have any idea about what i have to do.

@z3ntu 

![razergenie error](https://user-images.githubusercontent.com/36943374/47571771-bc331000-d90f-11e8-941e-ac24df50bb58.png)

**Comment by z3ntu** [comment]
Which distribution are you using? And how did you install RazerGenie?

**Comment by z3ntu** [comment]
Closing, as there has been no response.
