### ISSUE TITLE
I can't change the color of FN and Space keys

### ISSUE THREAD

**Issue by tildearrow** [z3ntu/RazerGenie#35]
It seems that when I change the colors of the Space and/or FN key(s), the changes are not reflected in the keyboard.
I've tested in the other 2 frontends and it works well there, so it's not a daemon bug.

RazerGenie:

[![spacefn.png](https://i.postimg.cc/2S05TF7D/spacefn.png)](https://postimg.cc/QFWsd7z4)

BlackWidow X Chroma:

[![fnprob.png](https://i.postimg.cc/dQRw4jJx/fnprob.png)](https://postimg.cc/3Wwswp4X)

**Comment by tildearrow** [comment]
Sadly, that is not the case. The BlackWidow X Chroma and newer keyboards do have lights under these keys. Please reopen.

**Comment by z3ntu** [comment]
Okay. Please follow https://github.com/z3ntu/RazerGenie#how-to-compile and except the `meson configure -Denable_experimental=true` run `meson configure -Dinclude_matrix_discovery=true`, and click the "launch matrix discovery" button in the newly compiled version of RazerGenie. Then click through the buttons and note down which label the button that sets the light of space/fn.

**Comment by tildearrow** [comment]
5_7, 5_12

(space and FN respectively)
