### ISSUE TITLE
Key remapping support

### ISSUE THREAD

**Issue by waytoomuchgaming** [z3ntu/RazerGenie#4]
Hello

So far, the keypad is correctly detected, i can manage to control the lights, but not the keys (i need to remap them). There is no menu or options to control them.
Also, pressing the keys of the keypad does nothing at all (i tested it in a text editor).

I then tried Keyboarding Master (https://bitbucket.org/conzar/keyboarding-master), with a little more luck : i can remap the keys, and they work nearly as intended (tested again in a text editor). By "nearly", i mean as soon as i use my regular keyboard, the next press on the keypad will be "funny" (can repeat forever, or being at the first press the initial key, at the second the remapped key), which end up as unusable for my needs (i need to use a regular keyboard + a keypad).

So, my guess is my keypad is physically working, i suppose it's not a material problem.

What should i do next ?
(i'm using Xubuntu 16.04)

**Comment by z3ntu** [comment]
Key remapping is not supported by the daemon yet (which this application relies on).

**Comment by Bifidus** [comment]
Ok... the supported list of the daemon page is misleading, then.
Thank you for the info!

**Comment by GabMus** [comment]
*shameless self advertisement*

But seriously, do the macros work on [razerCommander](https://github.com/gabmus/razercommander)? I have them implemented and last time I checked they **did** work.

**Comment by z3ntu** [comment]
At OpenRazer we now recommend to use https://github.com/sezanzeb/input-remapper . Closing this as it's not in-scope of OpenRazer or RazerGenie.
