### ISSUE TITLE
Razer BlackWidow Chroma V2 (es_ES) layout: 10

### ISSUE THREAD

**Issue by i5o** [z3ntu/RazerGenie#42]
`cat /sys/bus/hid/drivers/razerkbd/0*/kbd_layout`
`10`
![img_1232](https://user-images.githubusercontent.com/2650479/50531740-0726fa80-0aee-11e9-8d7f-70c19bf504f2.JPG)

**Comment by i5o** [comment]
Just FYI I no longer own this keyboard, but do own  https://github.com/z3ntu/RazerGenie/issues/91, so I can't help testing this issue. Thx :)

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
