### ISSUE TITLE
Release key for xUbuntu is expired

### ISSUE THREAD

**Issue by kenzierocks** [z3ntu/RazerGenie#44]
Akin to #43, the key for xUbuntu 18.10 is out of date:
```
$ curl -s http://download.opensuse.org/repositories/hardware:/razer/xUbuntu_18.10/Release.key \
 | gpg --with-fingerprint --show-key
pub   rsa2048 2014-09-16 [SC] [expired: 2019-02-01]
      E96C 496E 4E77 C159 C2FC  A053 062F 9FD4 D6D1 1CE4
uid                      hardware OBS Project <hardware@build.opensuse.org>
```

(I opened a new issue since it's a different repository, and the other one is technically fixed.)

**Comment by z3ntu** [comment]
I've triggered rebuilds for both 16.04 and 18.10, the others should be valid until 2021-03-28

**Comment by kenzierocks** [comment]
How long does it take a rebuild to go through? Still seeing the same key, http://download.opensuse.org/repositories/hardware:/razer/xUbuntu_18.10/ lists it as unchanged since October still.

**Comment by z3ntu** [comment]
The rebuilds seems to have completed but I don't know why the key didn't update...
