### ISSUE TITLE
Feature: configure functional keys on Razer keyboards

### ISSUE THREAD

**Issue by x1unix** [z3ntu/RazerGenie#45]
Hello, can you add a keybinding section for Razer keyboards?
Currently the single way to configure functional keys on BlackWidow Chroma is creating `.xbindkeysrc` file:

```
"playerctl play-pause"
  m:0x10 + c:193
  Mod2 + XF86Launch6
"playerctl next"
  m:0x10 + c:195
  Mod2 + XF86Launch8
"playerctl previous"
  m:0x10 + c:194
  Mod2 + XF86Launch7
```

It can be a simple frontend over `xbindkeys` tool.

**Comment by z3ntu** [comment]
This is a known limitation of the OpenRazer drivers - you should use the search feature at https://github.com/openrazer/openrazer/issues where you can find some other applications that you can use to map keys on your keyboard.
