### ISSUE TITLE
doesn't remember settings on restart

### ISSUE THREAD

**Issue by codeman101** [z3ntu/RazerGenie#46]
I love RazerGenie. In my opinion the interface is easier to navigate than the proprietary program on Windows. :) There's just one issue I've noticed that's annoying. If you use razergenie to set your color settings for your hardware, close the program and then go back into it, it doesn't save the settings you previously set. It always goes back to a default for everything. (including the sync devices option)

**Comment by z3ntu** [comment]
Yes, I know of that issue.
I've been working on a rewrite for openrazer (titled razer_test currently) that implements support for that (asking the daemon which colors (and effect) were set previously)

**Comment by codeman101** [comment]
All good. Take your time. I can manage in the meantime. Just wanted to mention it.

**Comment by z3ntu** [comment]
This should be solved now since quite a few OpenRazer versions.
