### ISSUE TITLE
Razer Naga Chroma not recognized 

### ISSUE THREAD

**Issue by Nostalgi4** [z3ntu/RazerGenie#47]
I have openrazer and RazerGenie installed but when I open the RazerGenie GUI and try to open custom editor I get this: https://imgur.com/RJIPo2y. I checked on openrazer's website and it shows that this device is supposed to be supported, so I am not sure if this is a bug or if I have things configured incorrectly. Any help would be appreciated!

**Comment by z3ntu** [comment]
Duplicate of #10
