### ISSUE TITLE
Support for Razer Orbweaver?

### ISSUE THREAD

**Issue by Quax1102** [z3ntu/RazerGenie#5]
Hi I just installed your software as I want to configure my Razer Orbweaver under Ubuntu 16.04. In first installed the driver package from OperRazer, then the deb package from your site. Razergenie is now installed and opens, then showing my Razer Orbweaver - howevere thats all, there's no possibility to change the settings. Just an icon in the sidebar showing my Orbweaver. Am I doing something wrong, or is the Orbweaver not supported? Or do I need to go through the "compile" part also?
Thanks for your help
cheers,
Peter

**Comment by z3ntu** [comment]
I've identified a few issues and am working on it :)

**Comment by z3ntu** [comment]
Thanks for the report! It will be fixed in the next version. You can try it already by checking out the repo and running the lines labeled as `How to compile` in the readme.
