### ISSUE TITLE
Razer BlackWidow Chroma (Nordic) layout

### ISSUE THREAD

**Issue by enteXeye** [z3ntu/RazerGenie#51]
RazerGenie tells me that my keyboard layout isn't supported and that I should open an issue here.

Picture of the keyboard
![IMG_20190518_174136](https://user-images.githubusercontent.com/25712657/57971956-0e637d80-7995-11e9-8e72-dc25736adf89.jpg)

**Comment by z3ntu** [comment]
You can try https://github.com/z3ntu/RazerGenie/pull/32 by running `sudo curl https://raw.githubusercontent.com/z3ntu/RazerGenie/55d68868834fcf8103fb3cbcd6f8bc3a590de6d4/data/matrix_layouts/razerdefault22.json -o /usr/share/razergenie/matrix_layouts/razerdefault22.json`

**Comment by z3ntu** [comment]
#32 is merged, closing.
