### ISSUE TITLE
Keyboard Layout (fr_FR) not supported for Cynosa Chroma

### ISSUE THREAD

**Issue by gubgubgub** [z3ntu/RazerGenie#52]
Hi,
I would like to open the custom editor, but this message appears :
![razer keyboard fr layout issue](https://user-images.githubusercontent.com/27416823/58440523-e08be080-80da-11e9-893d-2686a6fd948d.png)
…so I open an issue :)

Could you please add the fr_FR keyboard layout for the Cynosa Chroma ?

Here is a picture of my keyboard :
![IMG_20190527_233955886_01](https://user-images.githubusercontent.com/27416823/58440512-ceaa3d80-80da-11e9-8c24-d3517be939ad.jpg)

Did you need something else ?
Thank you very much for your help.

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
