### ISSUE TITLE
Add a way to permanently get rid of the "The OpenRazer daemon is not set to auto-start." warning

### ISSUE THREAD

**Issue by tildearrow** [z3ntu/RazerGenie#55]
I don't use the systemd service unit but rather let Polychromatic auto-start the daemon.

**Comment by z3ntu** [comment]
Sure, I can add an option on the preferences for that. But if you're not using systemd, you shouldn't get this popup at all; only a similar one when the daemon is not running.

**Comment by tildearrow** [comment]
Clarification: I am using systemd.
