### ISSUE TITLE
Please add keyboard layout (en_GB) for Razerblade 15 (2018)

### ISSUE THREAD

**Issue by kawmaiparis** [z3ntu/RazerGenie#56]
Your keyboard layout (en_GB) is not yet supported by RazerGenie for this keyboard. Please open an issue in the RazerGenie repository.

Please add (en_GB) for RazerBlade 15 2018 (Advanced Model)

Thank you!

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
