### ISSUE TITLE
Please add (pt_PT) keyboard layout for Razer Cynosa Chroma

### ISSUE THREAD

**Issue by PedroVictorCoding** [z3ntu/RazerGenie#57]

**Comment by z3ntu** [comment]
Could you please send me a picture of your keyboard so a layout file can be created for it?

**Comment by PedroVictorCoding** [comment]
Here is the picture! thanks for the help!
![20190723_204253](https://user-images.githubusercontent.com/47682329/61756586-9d708580-ad8a-11e9-8d81-8ba4d2cbcd53.jpg)

**Comment by PedroVictorCoding** [comment]
Is this picture good enough?

**Comment by z3ntu** [comment]
Yes, thanks.

**Comment by Samega7Cattac** [comment]
#63 already made a pull request

**Comment by Samega7Cattac** [comment]
PR have been merged

**Comment by z3ntu** [comment]
Ah yes, thanks for the reminder :)
