### ISSUE TITLE
Goliathus Extended Chroma Support

### ISSUE THREAD

**Issue by laurinneff** [z3ntu/RazerGenie#58]
I recently switched from polychromatic to razergenie, and would like if it supported my Goliathus Extended Chroma (Device image and hidden custom editor button)

**Comment by z3ntu** [comment]
Hi, for the device image to show correctly, I need to implement a new API in openrazer. The custom editor button should show though.

Could you install d-feet, go to the "Session Bus" tab at the top, enter `org.razer` into the search field, expand the device (if you have multiple you can look at the serial number shown in RazerGenie and use the correct one in d-feet) and expand all the sections (so there's a list of Method like getDeviceMode(), getDeviceName(), etc) and make a screenshot of that?

Additionally please give me with the output of `ls -al /sys/bus/hid/drivers/razermousemat/0*/`

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
