### ISSUE TITLE
Custom editor on Razer Blade Stealth (Late 2017) - matrix dimens: 6 16

### ISSUE THREAD

**Issue by mskrip** [z3ntu/RazerGenie#6]

**Comment by z3ntu** [comment]
Can you please make a (readable) picture of your keyboard with all keys visible and also the output of `cat /sys/bus/hid/drivers/razerkbd/0*/test`. Thanks for reporting!

**Comment by mskrip** [comment]
Ouput of `cat /sys/bus/hid/drivers/razerkbd/0*/test` is

```
030000
```

And picture of the keyboard:
![img_20171221_122550](https://user-images.githubusercontent.com/17459600/34254006-4dcd22f8-e64a-11e7-8af7-2175e7ead6e5.jpg)

**Comment by z3ntu** [comment]
Could you please run the script at https://github.com/openrazer/openrazer/blob/master/scripts/driver/keyboard_keys.py (change all the 22's to 16 first I think) and note down which keys light up with which matrix position.
So if you could do like:
> esc empty empty F1 F2 ...
^ empty 1 2 3

or something because I don't know which matrix positions access what keys.

**Comment by z3ntu** [comment]
But I have already finished the graphical part of your keyboard :) Just the matrix positions are missing now.
![image](https://user-images.githubusercontent.com/3768500/34256928-e84935b2-e657-11e7-9c46-bc5cceeaf4ec.png)

**Comment by mskrip** [comment]
Only keys that lit up are :
- row 0: F1 - F12
- row 1: 1 - ´
- row 2: W
- row 3: A, S, D
- arrow keys

**Comment by mskrip** [comment]
I am trying to run it again, but no keys light up this time.

**Comment by z3ntu** [comment]
Can you please test the application from the branch `feature/razerblade16`? Instructions are at the bottom of the readme but you might have to install some dependencies first (but meson should tell you what is missing).

**Comment by z3ntu** [comment]
The important part of testing is that all on-screen keys map exactly to the physical keys and light up correctly. :)

**Comment by mskrip** [comment]
Backspace and Enter keys do not light up.
Also the right part of the bottom row is not aligned correctly. `Alt gr` does not light up but on-screen `Alt gr` lights up physical `fn` key and the same for all the keys to the right of it (misaligned by one key, alt gr is first)

**Comment by mskrip** [comment]
That may be caused by the fact that there are 4 distinct arrow keys maybe. As on-screen `strg` button lights up left arrow.

**Comment by z3ntu** [comment]
Please pull the newest changes and try again 🙂

**Comment by z3ntu** [comment]
I know that arrow-down doesn't exist but that's another problem I have to tackle.

**Comment by mskrip** [comment]
`Backspace` works now, but `Enter` and `RShift` do not work. As for arrow-down, wouldn't it be enough to light up both up and down arrows with same on-screen button?

**Comment by z3ntu** [comment]
I've added a few extra buttons now, please tell me which one works 😉 
About the arrow keys: I'll figure something out but lighting two keys with one button would have to be implemented in RazerGenie separately so I'll just figure the two buttons on top of each other out.

**Comment by mskrip** [comment]
The rightmost `Enter` (enter4) and `RShift` (shitft3) on-screen buttons work now :) . BTW space key does not have lightning on the keyboard, but I'm not sure whether that is relevant.

**Comment by mskrip** [comment]
No, none of the space buttons do anything.

**Comment by z3ntu** [comment]
Dou you know if Razer Synapse can light up the space button?

**Comment by mskrip** [comment]
To my knowledge space button does not have LED to light up so I think it can't.

**Comment by z3ntu** [comment]
Okay I'll deactivate that button then.

**Comment by z3ntu** [comment]
Okay please verify again that everything works, then I can merge it to master :) (you might have to run `git fetch; git reset --hard origin/feature/razerblade16` as I have force-pushed that branch)

**Comment by mskrip** [comment]
Yes, everything (except the down arrow) works correctly.

**Comment by z3ntu** [comment]
I've added it now, it doesn't look particularly good but it should do the job for now. I'll probably look into using the QGridLayout instead of my nested QVBox- and QHBoxLayouts for fixing this and also making the enter key prettier.
![image](https://user-images.githubusercontent.com/3768500/34320016-e5060f26-e7ef-11e7-8bb5-6d6aff0b92bb.png)

**Comment by mskrip** [comment]
Yes :) everything works properly now. Great job!
