### ISSUE TITLE
Please add (fr_FR) keyboard layout for Razer BlackWidow Chroma V2

### ISSUE THREAD

**Issue by Synntix** [z3ntu/RazerGenie#60]
Hi, there is a picture of the keyboard for the layout.
![IMG_20190825_223110](https://user-images.githubusercontent.com/36386823/63655450-670e9780-c788-11e9-8443-0af8133378a3.jpg)
(The Razer key in top left is escape)

Thanks !

**Comment by vankasteelj** [comment]
#38

**Comment by z3ntu** [comment]
Yep, duplicate of #38 and will be fixed with #39
