### ISSUE TITLE
Why are packages only available for xubuntu?  

### ISSUE THREAD

**Issue by light24bulbs** [z3ntu/RazerGenie#62]
The .debs don't seem to work for other flavors of ubuntu or mint

**Comment by z3ntu** [comment]
They do, the wording in the openSUSE build service is xUbuntu because they mean "any" with the "x", so "any derivative of Ubuntu" basically (or *Ubuntu)

**Comment by light24bulbs** [comment]
That's....really weird, because xubuntu means something totally different.
https://xubuntu.org/ It's the flavor of Ubuntu that comes with xfce.  I'm
surprised they would make that mistake.

And the .deb doesn't work with a new Linux mint installation out of the
box: libQT conflicts.  But if you're not targeting mint, that's
understandable.

**Comment by light24bulbs** [comment]
I have to believe you've been misled on that and the build system is
misconfigured.  Here is a list of their build targets.  Xubuntu is a subset
of their Ubuntu target
https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets

**Comment by z3ntu** [comment]
They use different terminology there apparently.

See this time I asked in 2017:
![image](https://user-images.githubusercontent.com/3768500/67616596-2ad4d300-f7db-11e9-9644-5996276d7b5f.png)

**Comment by light24bulbs** [comment]
Very strange!  They must have had an internal misunderstanding at some
point.  Xubuntu has been around longer than they have.  I will write to
them asking about it.  Thanks for clarifying and for working on such a
great free product!

**Comment by z3ntu** [comment]
Thanks!

**Comment by z3ntu** [comment]
I've also just found https://github.com/openSUSE/open-build-service/issues/2089 , but maybe if enough people complain that the name is confusing (which it is!), they will consider changing it.
