### ISSUE TITLE
Issues opening custom editor

### ISSUE THREAD

**Issue by rafapaulin** [z3ntu/RazerGenie#64]
Device name: Razer Huntsman Elite - matrix dimens: 9 22

Unknown matrix dimensions 

Your keyboard layout (en_US) is not yet supported by RazerGenie for this keyboard

Neither one of these layouts was found in the layout file: de_DE, en_US, en_GB. Exiting.

**Comment by z3ntu** [comment]
Could you please follow https://github.com/z3ntu/RazerGenie#how-to-compile and replace the `meson builddir` command with `meson builddir -Dinclude_matrix_discovery=true` , and in the self-compiled RazerGenie there should be a button called "Launch matrix discovery". In that view, the first six rows should be standard but you have to tell me what the bottom three rows do, which buttons control what LED on the keyboard.

**Comment by Develon5543** [comment]
Hello! I'm not the issue starter, but I'd like to share the matrix with you using en_US and the Razer Huntsman Elite (9 22). I mapped out all the keys and mapped out the underglow rows. The "probably" corners are pretty accurate, but the color bleeding makes it a little hard to fully be sure. I hope to see this implemented ^^
[Razer Huntsman Color Mapping.txt](https://github.com/z3ntu/RazerGenie/files/4106793/Razer.Huntsman.Color.Mapping.txt)

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
