### ISSUE TITLE
You can open multiple copies of the Preferences dialog

### ISSUE THREAD

**Issue by tildearrow** [z3ntu/RazerGenie#66]
Pressing the Preferences button allows for opening multiple copies of the Preferences dialog, when it should focus it if it is already open.
(or is this intended?)

**Comment by z3ntu** [comment]
Neither, when the button is pressed I open the preferences window. Many applications solve this by making the preferences window Modal so you can't use the main application while in the settings. I guess that would solve this issue easily.

**Comment by z3ntu** [comment]
Dunno why GitHub failed to close this issue. The commits have been in git since 2020.
