### ISSUE TITLE
Wave speed

### ISSUE THREAD

**Issue by mruz** [z3ntu/RazerGenie#7]
Is there any possibility to change speed of Wave Lighting?
By default it's very fast 25 k/s I would like to set to minimum 1 k/s. I saw that option on Windows.

Keyboard: Razer BlackWidow X Chroma TE

**Comment by z3ntu** [comment]
This is not supported in the daemon. 
Depending on if this is a hardware or a software effect, support could be quite easy or pretty hard. Could you record packet captures (see https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) of you changing the wave speed in Synapse?

**Comment by z3ntu** [comment]
Closing as there is no answer.
