### ISSUE TITLE
BlackWidow Ultimate 2012 missing Custom Editor

### ISSUE THREAD

**Issue by FagSoft** [z3ntu/RazerGenie#71]
Just installed RazerGenie from source, but I can't seem to find the Custom Editor to configurate the macro keys. Only adjusting the LED intensity and pulse/static. I don't have any error messages either.
Is there anything I can do to fix this?

See image and OS/run details below. If you need more information, please let me know.

![image](https://user-images.githubusercontent.com/3675554/78227050-f7eee380-74cc-11ea-817e-ec2eaade48bd.png)

```
$ builddir/src/razergenie 
qt5ct: using qt5ct plugin
Translation loaded: false
"IO1151038101996"
"Razer BlackWidow Ultimate 2012"
libpng warning: iCCP: known incorrect sRGB profile
"keyboard"
CURRENT LOCATION:  "0"
Brightness: 7.06
inotify_add_watch("~/.config/qt5ct") failed: "No such file or directory"
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
```

**Comment by z3ntu** [comment]
The "custom editor" in RazerGenie is for configuring per-key lighting (which your device doesn't have I think).
I know that [razerCommander](https://github.com/gabmus/razercommander) has pretty good macro support (compared to all other frontends at least^^) so you should give that a try.

**Comment by FagSoft** [comment]
Ah, seems I've misunderstood things a bit. You're right about the per-key lighting.
Thanks for the answer, and the link to the proper application. Much apprecaited.

**Comment by z3ntu** [comment]
Closing this issue then. Macro support & key remapping is definitely where openrazer lacks currently and it's on the roadmap for some time in the future.
