### ISSUE TITLE
Your keyboard layout (Nordic) is not yet supported by RazerGenie.

### ISSUE THREAD

**Issue by HughDaniels23** [z3ntu/RazerGenie#72]
Could you please add support for this layout?
im providing images of the layout keys
![2](https://user-images.githubusercontent.com/63109358/78370337-ceb27e00-75c6-11ea-9cdc-6020d7e82890.png)
![3](https://user-images.githubusercontent.com/63109358/78370350-d3773200-75c6-11ea-9e75-770ab95332fc.png)
![4](https://user-images.githubusercontent.com/63109358/78370362-d7a34f80-75c6-11ea-9105-521202adfdec.png)
![unknown](https://user-images.githubusercontent.com/63109358/78370381-db36d680-75c6-11ea-9437-3ce41ad5bcd0.png)
![unknown1](https://user-images.githubusercontent.com/63109358/78370392-de31c700-75c6-11ea-9a1e-ed20500f382f.png)

**Comment by z3ntu** [comment]
Hi, did the message say "razerdefault22" by any chance? Then this should already be available in git master and will be a part of the next version (#32).

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
