### ISSUE TITLE
Add custom editor support for Orbweaver Chroma

### ISSUE THREAD

**Issue by chabad360** [z3ntu/RazerGenie#73]
Now that openrazer/openrazer#1072 was merged, can the custom editor be enabled for the Orbweaver Chroma?

**Comment by chabad360** [comment]
Using the matrix discovery feature shows which keys correspond to which buttons (note the last row):

```
| 1_1 | 1_2 | 1_3 | 1_4 | 1_5 |
| 2_1 | 2_2 | 2_3 | 2_4 | 2_5 |
| 3_1 | 3_2 | 3_3 | 3_4 | 3_5 |
| 4_1 | 4_3 | 4_4 | 4_5 | 4_6 |
```

I would attempt to make a PR for this, but I don't know C++ at all.

**Comment by chabad360** [comment]
Also on another note, `Profile LED 3` is actually the first of the 3 LEDs not the last (the other two are fine). Not sure if that is a problem that's due to openrazer or not.

**Comment by z3ntu** [comment]
The layouts are saved in https://github.com/z3ntu/RazerGenie/tree/master/data/matrix_layouts so you should be able to copy on of the jsons and adjust it to your needs. If it's not self-explanatory, you can take a look at https://github.com/z3ntu/RazerGenie/wiki/Keyboard-layout-files :)

**Comment by chabad360** [comment]
@z3ntu Thanks for that, but, I'm being told to add an issue to add the the keypad, to quote:

> Please open an issue in the RazerGenie repository. Device type: keypad

And from what I see in your code, it wont let me go past that unless some other stuff is done...

**Comment by chabad360** [comment]
Regardless, I've attempted to get this to work (on at least a rudimentary level), and I've been successful (to a point). I've managed to get it working, by including the keypad in keyboard `if`.
This pretty much worked, except that openrazer doesn't give a keyboard layout for it resulting in an error for lack of keyboard layout. I worked around this issue by removing that check...

All in all, not a perfect implementation, and will probably need to be done very differently after openrazer/openrazer#880 (primarily due to the thumb buttons).

**Comment by hesa2020** [comment]
Hello i am running the Tartarus V2, i am getting the Device type keypad not implemented error, is there anywhere i can get the build you are talking about @chabad360

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
