### ISSUE TITLE
Custom editor support for BlackWidow Chroma (ru_RU)

### ISSUE THREAD

**Issue by theskymaybe** [z3ntu/RazerGenie#77]
Hello guys!
First, just wanted to say that your software is awesome! I was also wondering if it's possible to add custom editor support for ru_RU layout for BlackWidow Chroma. 
Here's a photo of my keyboard layout:
![keyboard_layout](https://user-images.githubusercontent.com/11465715/82129474-cb1c3480-97cb-11ea-9e07-701c40770b03.jpg)
Thanks a lot in advance!

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
