### ISSUE TITLE
RazerGenie wont build any more 

### ISSUE THREAD

**Issue by hedmo** [z3ntu/RazerGenie#78]
today i was rebuilding RazerGenie and found out it fails .here is the log
[build.log](https://github.com/z3ntu/RazerGenie/files/4639808/build.log)

regards

**Comment by toluschr** [comment]
Since the latest release, the author of this project added two new dependencies. `razer_test` and `libopenrazer`. You will need to compile and install both of them first.

**Comment by hedmo** [comment]
does that mean o loose openrazer?

**Comment by toluschr** [comment]
Why would that mean loosing openrazer?

**Comment by hedmo** [comment]
"A work-in-progress replacement for OpenRazer" or they are working together ?

**Comment by toluschr** [comment]
It just gives you an option in the settings to use the other backend, which is supposed to be faster. You can still use openrazer if you want to.

**Comment by hedmo** [comment]
okej..checking it out ..

thanks for the info.

**Comment by z3ntu** [comment]
The (fixed) razer_test dependency is just for the header https://github.com/z3ntu/razer_test/blob/master/include/razer_test.h , the rest of the communication happens exclusively through dbus. And yes, the previously included libopenrazer library is now in a separate repository https://github.com/z3ntu/libopenrazer .

**Comment by hedmo** [comment]
@z3ntu i have made a ebuild that pulls in openrazer if i want full features(openraser) if i want to add 
the deps for it .i like to get a full razer_test up and running without openrazer and try to contribute
to get razer_test a go. as i have the razer hyperflux,razer goliathus,razer orbweaver chroma,razer firefly and the razer ouroboros.  i like to see them running on razer_test. if you can give me some info how to get them to run i am glad to fork razer_test and try to make them work as i did with the hyperflux...by the way why do want to remove the  dependency for razer_test?.if one want to use  RazerGenie..... pull razer_test in. it is good for the project and i think go all meson with RazerGenie and try to pull out openrazer....

regards hedmo
