### ISSUE TITLE
Changing effect wrong device

### ISSUE THREAD

**Issue by Samega7Cattac** [z3ntu/RazerGenie#79]
I have a Razer Kraken 7.1 Chroma and a Blackwindow chroma and when I change the effect of the headset it also changes the keyboard to the same effect.
Need to change the keyboard effect again.

**Comment by z3ntu** [comment]
There's a checkbox at the bottom of the UI called "Sync devices" which you can disable to stop that behavior.

**Comment by Samega7Cattac** [comment]
window was to large, making full screen fits everything
