### ISSUE TITLE
razerblade16.json is missing US layout

### ISSUE THREAD

**Issue by JungleCatSW** [z3ntu/RazerGenie#8]
I'm having  problem where the custom mapping on my blade qhd, isn't mapping some keys at all. The left and keys of the keyboard tab, caps and shift aren't lighting up.

Do I need to supply a matrix json file for my layout ?
My spec is Blade 14 QHD with US layout.

Is there a way to generate the mapping too ?

**Comment by z3ntu** [comment]
If your Blade has the usb id 1532:020F then yes, the us keyboard layout has to be added to the razerblade16.json file.
I'll try to create a UI for nicely figuring out which matrix id is behind each key. Also you'd need the content of https://github.com/openrazer/openrazer/pull/452 as my application has no way of knowing your actual keyboard layout currently unfortunately. That PR isn't finished yet though.

**Comment by z3ntu** [comment]
You can check out the branch `feature/matrix-discovery`, follow [the compilation instructions](https://github.com/z3ntu/RazerGenie/tree/feature/matrix-discovery#how-to-compile) and replace the meson configure line with `meson configure -Dinclude_matrix_discovery=true`. Then there should be a button called 'Launch matrix discovery' next to the 'Open custom editor' button.

**Comment by JungleCatSW** [comment]
okay thanks!

**Comment by JungleCatSW** [comment]
yes that picture is  020f what i have. I couldn't get meson/qt setup yet but I wrote a python script to set the key colors so I have the matrix codes. I will make a JSON from it manually and post!

**Comment by z3ntu** [comment]
https://github.com/z3ntu/RazerGenie/wiki/Dependencies has a list of dependencies for Ubuntu and Arch that need to be installed in order for the application to be compiled.

**Comment by z3ntu** [comment]
bump

**Comment by z3ntu** [comment]
Bump. The commit needed for getting the keyboard layout is merged in openrazer and #9 in this repo is also merged.

**Comment by z3ntu** [comment]
I'm closing this because this issue has not had recent activity.
