### ISSUE TITLE
"The OpenRazer daemon is not installed"

### ISSUE THREAD

**Issue by gemcosta** [z3ntu/RazerGenie#83]
Hi,

I'm running a fresh install of Pop!_OS 20.04 LTS. As you may know, this is essentially Ubuntu. 

I went through OpenRazer's installation steps for Ubuntu as described [here](https://openrazer.github.io/#download). I get a message from Terminal as follows:

```
gemcosta@pop-os:~$ sudo apt install openrazer-meta
[sudo] password for gemcosta: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openrazer-meta is already the newest version (2.8.0-0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

This suggests I have successfully installed Openrazer. Then when  I open RazerGenie, I get the following message:

![Screenshot from 2020-07-11 18-17-54](https://user-images.githubusercontent.com/11170013/87236845-edcd6280-c3a2-11ea-9375-d61c02424025.png)

Perhaps I am still too new to understand what this means, but I can't seem to find any good direction as to what I should try next. Any help would be appreciated so that I can use my Razer devices with my new PC :)

**Comment by z3ntu** [comment]
Can you give me the output of `openrazer-daemon -Fv` ?

**Comment by gemcosta** [comment]
Thanks for the reply. That actually told me how to fix it. Seems that for some reason I was not in the `plugdev` group. 

I ran `sudo usermod -a -G plugdev userName` and rebooted. Now RazerGenie opens up as expected! Thanks for the tip.
