### ISSUE TITLE
The OpenRazer daemon is not installed

### ISSUE THREAD

**Issue by ggascon** [z3ntu/RazerGenie#84]
I'm trying to run RazerGenie in macOS Catalina and I getting the follow message:
<img width="805" alt="RazerGenie daemon is not installed" src="https://user-images.githubusercontent.com/23144200/87347117-f9f82200-c552-11ea-8dc9-37d937df9d90.png">

I have successfully installed razer_test from brew and also started the service. _brew services list | grep razer_test_ output:

`razer_test started root    /Library/LaunchDaemons/homebrew.mxcl.razer_test.plist`

I selected razer_test as a Daemon backend in RazerGenie settings.
<img width="602" alt="RazerGenie settings" src="https://user-images.githubusercontent.com/23144200/87347298-404d8100-c553-11ea-9c76-cfcc01e642b1.png">
 
I'm sure I'm doing something wrong, but I can't figure out what it is. 
Any help would be appreciated. Thanks.

**Comment by z3ntu** [comment]
I think the problem is that you've started the service (`razer_test`) as root instead of as your user, see https://github.com/z3ntu/razer_test/wiki/macOS

**Comment by ggascon** [comment]
I've started the service as a standard user and I get the same result.

`razer_test started ggascon /Users/ggascon/Library/LaunchAgents/homebrew.mxcl.razer_test.plist`

<img width="805" alt="Daemon is not installed" src="https://user-images.githubusercontent.com/23144200/87430027-e5646a00-c5e4-11ea-9b8a-d81374eb7919.png">

**Comment by z3ntu** [comment]
Can you check in system monitor (or whatever it's called) which user the process `razer_test` runs as? `ps aux | grep razer_test` could also reveal this.

Next check the output of the command `qdbus` , I think that should be installed by default with Qt5.

**Comment by ggascon** [comment]
`razer_test`process does not appear in the activity monitor and neither when I run `ps aux | grep razer_test`, but in brew services list.

`razer_test started ggascon /Users/ggascon/Library/LaunchAgents/homebrew.mxcl.razer_test.plist`

`qdbus`output:

`dbus[71650]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
Could not connect to D-Bus server: org.freedesktop.DBus.Error.NoMemory: Not enough memory`

Sorry, I'm lost.

**Comment by z3ntu** [comment]
Does the `dbus` service run? I'm guessing it doesn't and razer_test doesn't launch because of that but brew services still thinks it's running - referring to https://github.com/z3ntu/razer_test/wiki/macOS again

**Comment by ggascon** [comment]
Ok, for some reason brew services start dbus doesn't work. I started from launchctl and it worked.

Thanks.

**Comment by z3ntu** [comment]
Weird. Nice that it's working now :)
