### ISSUE TITLE
translation not loaded

### ISSUE THREAD

**Issue by brown78** [z3ntu/RazerGenie#86]
Hello,

I recently cloned razer_test and RazerGenie to /usr/bin and installed everything. From that point everything worked, but then I set the option to download images in preferences and now every time I cd in /usr/bin/RazerGenie/build and run ./src/razergenie it stucks with "translation loaded: false"
I then changed download images to false in ~/.config/razergenie/RazerGenie.conf but still the same, I can not run RazerGenie again to change settings. Any hints on how to make it work again?
Besides that, the changes I have made are persistant, the colors stick when I shutdown the PC (running Manjaro). With Synapse3 on Windows the settings are reverted to stock immedialty when I hit restart or shutdown...

**Comment by z3ntu** [comment]
Hi, is this still an issue? The translations not getting loaded is irrelevant for debug builds (except you want translations in that build). I'm not sure why or where it hangs on your machine, I haven't seen that behavior myself yet.

**Comment by brown78** [comment]
Hello,

no issue anymore. I don't know what went wrong. It works now except 
settings are not saved and lights on the mouse are out after reboot.

Am 27. September 2020 13:42:23 schrieb Luca Weiss <notifications@github.com>:

**Comment by z3ntu** [comment]
Settings not getting saved should be solved with the next version. Thanks for the reply.
