### ISSUE TITLE
Razer Naga Trinity -- No Lighting Effects -- no Macro Support

### ISSUE THREAD

**Issue by 1412kauti** [z3ntu/RazerGenie#88]
No Lighting Effects at all
![2020-07-25_02-22](https://user-images.githubusercontent.com/22842439/88445917-cb652b80-ce1d-11ea-893c-458c19ceadcb.png)
N then theres the Side Plates a.k.a the macros
![1](https://user-images.githubusercontent.com/22842439/88445954-1e3ee300-ce1e-11ea-8f95-54eb52e5dd10.png)

**Comment by z3ntu** [comment]
The latest version of RazerGenie only supports the main lighting zone (where you can change Static to something else) at the moment, the next version will support all lighting zones the device has.

The message from the second screenshot is covered in issue #10
