### ISSUE TITLE
Razer Blade Stealth RZ09-0196 No device was detected

### ISSUE THREAD

**Issue by VonZane** [z3ntu/RazerGenie#89]
I'm *very* new to Linux in general, so please excuse my "noobness" on this. 
I'm trying to run RazerGenie using Linux Mint 20 on my Razer Blade Stealth RZ09-0196 (Early 2017). I checked the OpenRazer compatibility list, and it looks like it should work. 

When I launch RazerGenie, it says: 
"No device was detected
The OpenRazer daemon didn't detect a device that is supported. This could also be caused due to a misconfiguration of this PC."

**Comment by VonZane** [comment]
Oh, not sure if this helps any, but I use the US Dvorak keyboard layout.

**Comment by z3ntu** [comment]
Hi, is this still an issue?

**Comment by z3ntu** [comment]
Closing since there was no answer since 2 years ago.
