### ISSUE TITLE
Support for Razer Ornata Chroma en_GB in custom editor

### ISSUE THREAD

**Issue by mashedkeyboard** [z3ntu/RazerGenie#93]
Hi folks, support for en_GB Ornata Chroma would be awesome!

`cat /sys/bus/hid/drivers/razerkbd/0*/kbd_layout` returns `06`.

A photo of the layout is below:

![image](https://user-images.githubusercontent.com/16772519/92041417-186ae480-ed70-11ea-82bc-0208b8b6a56f.png)

Ta!

**Comment by z3ntu** [comment]
Hi,

The latest version of [RazerGenie v1.0.0](https://github.com/z3ntu/RazerGenie/releases/tag/v1.0.0) has just been released.
The new version allows you to open the Custom Editor regardless of whether a dedicated layout exists for your device. Please try the new version and see if that fulfils your use case.

If not, please let me know and I'll reopen the issue and will try to get a layout for your specific device into RazerGenie. For keyboards it should be sufficient if you can take a photo of your keyboard and post it here. For other devices please use the custom editor (with the default fallback layout) to map which button in the UI controls what LED on the device and share it with me.

Thank you!
