### ISSUE TITLE
RazerGenie-0.9.0 Detected file collision(s):

### ISSUE THREAD

**Issue by hedmo** [z3ntu/RazerGenie#96]
hi 
To day i updated RazerGenie but -

`* Detected file collision(s):
 * 
 *      /usr/lib64/libopenrazer.so.0.0.1
 *      /usr/lib64/libopenrazer.so
 *      /usr/lib64/libopenrazer.so.0
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * dev-libs/libopenrazer-20200514:0::hedmos-overlay
 *      /usr/lib64/libopenrazer.so
 *      /usr/lib64/libopenrazer.so.0
 *      /usr/lib64/libopenrazer.so.0.0.1
`
regards hedmo

**Comment by z3ntu** [comment]
0.9.0 is still based on the old codebase (branch "master-old") where RazerGenie bundles libopenrazer.

I believe you also partially have the new version (now "master", previously "razer_test") installed which provides the same files and conflicts. I'd recommend you (except you don't want the new version) to rebuild your RazerGenie & libopenrazer version from latest master and the conflicts should go away.

**Comment by hedmo** [comment]
@z3ntu thanks for the fast reply. as you can see in my post libopenrazer is the latest at i am using your latest commits when i build them and not live versions.the latest commit you did for libopenrazer was 20200514 and that is  the same  as download via git clone and build as far as i can say?. correct me if i am wrong or did not understand.

regards

**Comment by z3ntu** [comment]
In other words:

If you want to use RazerGenie 0.9.0, uninstall the libopenrazer package and use RazerGenie 0.9.0 (this includes libopenrazer)

If you want to use RazerGenie from git master (the new one with razer_test support) then this is not 0.9.0 as 0.9.0 derives from the old codebase.

**Comment by hedmo** [comment]
thanks for clarifying . so for me as i still  want to have the razer_test support . i dont have a 0.9.0 release and have to use commits to update  RazerGenie ? . so my release will be named  RazerGenie-0.9.0_p20208022 ? or is that one still a 0.8.1_p20208022?

**Comment by z3ntu** [comment]
Not 100% sure what you mean, but if you want to have razer_test support then just ignore the 0.9.0 release completely, it's not relevant to you at all. Just build from git master and everything should be fine.
