### ISSUE TITLE
 PGP signatures could not be verified!

### ISSUE THREAD

**Issue by 1m-N00b** [z3ntu/RazerGenie#97]
# Environment
- OS: Arch Linux x86_64
- Kernel: 5.8.10-arch1-1
- Package Manager:AUR(with yay)
- [package](https://aur.archlinux.org/packages/razergenie/?O=10&PP=10)

# Details
An error occurs with pgp authentication as shown in the [image](https://imgur.com/slD38oF).

**Comment by z3ntu** [comment]
Please read the [stickied AUR comment](https://aur.archlinux.org/packages/razergenie#pinned-597121):

> If you are having problems installing this package due to signature verification, please run the below before running makepkg:
> 
> gpg --keyserver hkps://keys.openpgp.org --recv-keys BD04DA24C971B8D587B2B8D7FAF69CF6CD2D02CD

**Comment by 1m-N00b** [comment]
Thanks for the quick response.
I tried the pgp proof in the latest comment before and it didn't work, but I did it as you said in your comment and it worked.

**Comment by sleeyax** [comment]
I had the same issue and the suggested command didn't work for me as it always resulted in `gpg: keyserver receive failed: Server indicated a failure`. I somehow fixed it by turning on my VPN. Digging further into it, it's most likely related to a DNS issue so if anyone who is reading this is having the same issue I'd suggest to try setting your DNS setting to something else like google DNS `8.8.8.8`.
