### ISSUE TITLE
Implement Ripple effect on Chroma

### ISSUE THREAD

**Issue by Saruspete** [z3ntu/RazerGenie#99]
Hello,

It seems to be missing the effect I love most: **ripple**
https://www.youtube.com/watch?v=i4doQjRRz2o
https://www.youtube.com/watch?v=k4fW9DqcIZ4#t=2m50

They are shown from the `capabilities_to_cpp.sh` :
```
capabilities.insert("lighting_starlight_single", hasCapabilityInternal("razer.device.lighting.chroma", "setStarlightSingle"));
capabilities.insert("lighting_starlight_dual", hasCapabilityInternal("razer.device.lighting.chroma", "setStarlightDual"));
capabilities.insert("lighting_starlight_random", hasCapabilityInternal("razer.device.lighting.chroma", "setStarlightRandom"));

capabilities.insert("lighting_ripple", hasCapabilityInternal("razer.device.lighting.custom", "setRipple"));
capabilities.insert("lighting_ripple_random", hasCapabilityInternal("razer.device.lighting.custom", "setRippleRandomColour"));

capabilities.insert("lighting_pulsate", hasCapabilityInternal("razer.device.lighting.bw2013", "setPulsate"));
```

Thanks a lot

**Comment by z3ntu** [comment]
Hi, can you please tell me what device you're using (output of `lsusb | grep 1532` is useful for that) and which version of RazerGenie you're using (v0.9.0?).
Generally the ripple effect is supported in v0.9.0 for devices that have it supported in openrazer.

**Comment by Saruspete** [comment]
Hello,

For the device, it's a blackwidow chroma, that had it working well on windows since many years.

```
$ lsusb -v -d 1532:

Bus 001 Device 002: ID 1532:0203 Razer USA, Ltd BlackWidow Chroma
Device Descriptor:
[ ... ]
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0203 BlackWidow Chroma
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer BlackWidow Chroma
```

About the version, I'm using the git:master (and I see the latest commit, 8b60b6535e94b25ac72bbae18ef9048acae91bb9 ).
However, when I do a fresh git clone + git describe (or git describe --tags), I'm having `v0.7-109-g8b60b65`.  In the commit history, the latest annotated tag is indeed v0.7, but --tags should give the `v0.9-xxx` at least.
In the 

Then when I `git checkout v0.9.0` , then git describe shows me correctly v0.9.0

I rebuilt the package from there, and now I indeed have the ripple effect !

Is there some issue with the master branch ?

**Comment by Saruspete** [comment]
There seems to be a sync issue between the `master` and `master-old` branches and they have diverged: 
[This branch is 24 commits ahead, 85 commits behind master.](https://github.com/z3ntu/RazerGenie/compare/master-old)

**Comment by z3ntu** [comment]
Yes, the master branch contains somewhat of a rewrite of RazerGenie, and I don't have a great concept for integrating the ripple effect there yet. It'll definitely come back before the next release though.
Also v0.9.0 (a release that needed to be done because of several issues) is based on master-old and the new master was branched from some older point. But all important parts (matrix layouts, translations, etc) should be present in both branches.

I'll close this issue I guess - ripple will definitely come back!
